### ISSUE TITLE
HTTP Status Codes

### ISSUE THREAD

**Issue by EgoistDeveloper** [jikan-me/jikan#101]
I don't want to make requests for 404 and so on again because my IP address can be blacklisted because of unnecessary requests. Generally, if we know HTTP status codes, we can act more consistent.

**Comment by irfan-dahir** [comment]
Your IP isn't blacklisted, Jikan's is rate limited temporarily. This returns HTTP Status 429. 
Check the headers, HTTP status is there.

**Comment by irfan-dahir** [comment]
Closing this discussion. If you wish to reply, please re-open this issue.
