### ISSUE TITLE
null score and amount of ratings on obscure mangas

### ISSUE THREAD

**Issue by Sacules** [jikan-me/jikan#102]
Before finding about this project, I tried parsing mangas on my own with Beautiful Soup on Python 3, and encountered a problem I see here as well. It seems that with some obscure mangas, the `'score'` and `'scored_by'` attributes are `null` due to a different formatting than what more popular ones use. Instead of being contained like usual,

`<span itemprop="ratingValue">6.75</span>`
 `<span itemprop="ratingCount">235</span>`,

they are formatted in this way:

```
<div class="po-r js-statistics-info di-ib" data-id="info1">
  <span class="dark_text">Score:</span>
  7.47
  
  <sup>
    <small>1</small>
  </sup>
  
  <small>(scored by 15 users)</small>
    ...
</div>
```

**Comment by irfan-dahir** [comment]
Hi @Sacules , thanks for the input! MAL finds itself not following standard HTML and is very inconsistent most of the time.

I'll go ahead and add a patch for this. You've already provided a snippet, but I still require the ID or link to the manga with such formatting for overall testing. Thanks!

**Comment by Sacules** [comment]
I first noticed it on this one:
https://myanimelist.net/manga/96896/Tensai-tachi_no_Kyouen

PS: I also noticed I get 404 responses on this (https://myanimelist.net/manga/104346/Adventure_Broadcasting_Station), should I open an issue for it?

**Comment by irfan-dahir** [comment]
Awesome, thanks!

The latter one seems to be returning a parsing error `"error": "date_format() expects parameter 1 to be DateTimeInterface, boolean given"`

This is related to the abnormal date MAL is going with here `Published: Jan 20, 1950 to 10, 1951`, I'll go ahead and ping another related issue to this so no need to. #99

**Comment by irfan-dahir** [comment]
Fixed.
