### ISSUE TITLE
Double quotes in shows not contained

### ISSUE THREAD

**Issue by UnderscoreNorth** [jikan-me/jikan#121]
Shows with double quotes in their name like https://myanimelist.net/anime/31894/The_iDOLMSTER_Million_Live_Dreaming_Animation_PV will cause the json to fail to parse. This also affects shows that have that show in the related section, like https://myanimelist.net/anime/10278/

**Comment by irfan-dahir** [comment]
I'll look into why it's not properly converting it to valid JSON.

**Comment by irfan-dahir** [comment]
Issue has been fixed and pushed to the development branch. The patch will be available from REST 2.2.
