### ISSUE TITLE
a logo or image for the api?

### ISSUE THREAD

**Issue by ImUrX** [jikan-me/jikan#130]
i recently started using this api for my bot on discord instead of scrapping, i think if i ever surpass the ratelimit i will just host it myself, but i really want to credit the api itself, do you have a nice image or something to represent it instead of just the name?

**Comment by ImUrX** [comment]
thanks! they seem very nice, btw you should use one of them for the README.md

**Comment by irfan-dahir** [comment]
Good idea! Will do.
