### ISSUE TITLE
Broken manga

### ISSUE THREAD

**Issue by paulo27ms** [jikan-me/jikan#131]
Hey, just wanted to let you know that all these manga are broken: (there's 2 more but I'm lazy to see which they were exactly)
https://api.jikan.me/manga/36899
https://api.jikan.me/manga/37045
https://api.jikan.me/manga/37555
https://api.jikan.me/manga/38097
https://api.jikan.me/manga/40029
https://api.jikan.me/manga/42305
https://api.jikan.me/manga/43711
https://api.jikan.me/manga/43831
https://api.jikan.me/manga/46006
https://api.jikan.me/manga/48797
https://api.jikan.me/manga/51113
https://api.jikan.me/manga/55003
https://api.jikan.me/manga/56113
https://api.jikan.me/manga/57219
https://api.jikan.me/manga/57341
https://api.jikan.me/manga/58691
https://api.jikan.me/manga/59141
https://api.jikan.me/manga/61411
https://api.jikan.me/manga/62573
https://api.jikan.me/manga/63645
https://api.jikan.me/manga/65543
https://api.jikan.me/manga/66185
https://api.jikan.me/manga/66895
https://api.jikan.me/manga/67099
https://api.jikan.me/manga/68445
https://api.jikan.me/manga/69365
https://api.jikan.me/manga/74129
https://api.jikan.me/manga/79707
https://api.jikan.me/manga/79919
https://api.jikan.me/manga/80035
https://api.jikan.me/manga/81649
https://api.jikan.me/manga/82035
https://api.jikan.me/manga/85735
https://api.jikan.me/manga/86048
https://api.jikan.me/manga/86092
https://api.jikan.me/manga/86094
https://api.jikan.me/manga/86098
https://api.jikan.me/manga/86099
https://api.jikan.me/manga/86100
https://api.jikan.me/manga/87501
https://api.jikan.me/manga/87524
https://api.jikan.me/manga/89766
https://api.jikan.me/manga/90735
https://api.jikan.me/manga/90836
https://api.jikan.me/manga/91811
https://api.jikan.me/manga/92637
https://api.jikan.me/manga/94101
https://api.jikan.me/manga/94953
https://api.jikan.me/manga/98788
https://api.jikan.me/manga/101262
https://api.jikan.me/manga/107888
Keep up the good work.

**Comment by irfan-dahir** [comment]
Wow, thank you!
