### ISSUE TITLE
PHP 5 type hint can only be NULL

### ISSUE THREAD

**Issue by guangrei** [jikan-me/jikan#133]
hi, i created a [wordpress plugins](https://github.com/anigrab/wp-anigrab) with jikan,
the plugins is work properly in php 7 but when test with php  `5.9`  there are error

```
Fatal error: Default value for parameters with a class type hint can only be NULL in /home/ubuntu/workspace/wp-content/plugins/wp-anigrab/vendor/jikan-me/jikan/src/Jikan.php on line 80
```
i have tried with jikan version  `dev-master` , `1.15.5` ,  `1.2.0` get same result

**Comment by irfan-dahir** [comment]
Hi, Jikan makes use of features added in PHP 7.0 and onwards. It doesn't support lower versions of PHP.

Type Hinting is a feature added in 7.0, hence why you get that error for 5.9.

**Comment by irfan-dahir** [comment]
Hi, sorry but I won't be adding an extra support for older PHP versions. I don't have the time to maintain another branch after it. Please feel free to fork the project and use the tool to backport it.

**Comment by guangrei** [comment]
oh ok, thanks for great works 😇
