### ISSUE TITLE
User List of Anime

### ISSUE THREAD

**Issue by Cleverdawn** [jikan-me/jikan#134]
Hi, your project looks much nicer to use than the shitty XML API of MyAnimeList and seems to be updated very often :D  But I'm not sure but it seems there is no way to still fetch user data/user anime list with it right ? 
Do you plan to integrate it later in the project ?

I could use your apiary.io api with Kitsu light JSON:API framework : https://github.com/wopian/kitsu/tree/master/packages/kitsu

**Comment by Cleverdawn** [comment]
Yes I've seen this request in MAL forums but were saying it was undocumented (back in 2013) xD I can't even look at MAL API documentation page more than a minute without burning my eyes so I'm very glad to find other projects like this :) 
Still thanks for the advice :) , I'll follow your development

**Comment by irfan-dahir** [comment]
Indeed, what's worse is going through MAL's HTML. 🤮
Likewise, will follow yours as well. :)
Good day!
