### ISSUE TITLE
Must be an instance of Jikan\\String, string given

### ISSUE THREAD

**Issue by gijsdejonge** [jikan-me/jikan#135]
I get this error when trying to call an anime:
`PHP Catchable fatal error:  Argument 1 passed to Jikan\\Jikan::Anime() must be an instance of Jikan\\String, integer given, called in [DIR]/index.php on line 9 and defined in [DIR]/vendor/jikan-me/jikan/src/Jikan.php`

With this code:
```
<?php
require_once(__DIR__.'/vendor/autoload.php');

$jikan = new Jikan\Jikan;

$anime = $jikan->anime(1);
var_dump($anime->response);
```

It looks exactly the same as in the examples. If I try to send a string instead of an int it still gives the same error. What am I doing wrong?

**Comment by irfan-dahir** [comment]
Hi, please change the composer settings to require from the `development` branch. I've pushed a patch which should fix the problem albeit I'm not sure why you're facing it in the first place.

Let me know if it still persists.

**Comment by gijsdejonge** [comment]
It was because I was using PHP5. I updated to PHP7 and now it works. Thanks for the help!

**Comment by assintates** [comment]
But why though.

**Comment by irfan-dahir** [comment]
@assintates You ninja'd me. x)
Why what?

**Comment by assintates** [comment]
🇸 🇪 🇳 🇩   🇳 🇺 🇩 🇪 🇸
