### ISSUE TITLE
Source of hosted version

### ISSUE THREAD

**Issue by Fidelix** [jikan-me/jikan#137]
Hi, any chance we can get the source of the hosted version so we can possibly host it (as a microservice) to minimize external dependencies?

Thanks,

**Comment by assintates** [comment]
Just use the dev branch.

**Comment by Fidelix** [comment]
@assintates you mean this one?
https://github.com/jikan-me/jikan/tree/development

Doesn't look like the right one.

**Comment by assintates** [comment]
Yes that's where latest commits go and there's no difference in the hosted version.

**Comment by assintates** [comment]
Also lemme ask you what do you mean by hosted version the one that's running on server?

**Comment by Fidelix** [comment]
@assintates the one that you seem to host here: http://api.jikan.moe/

Presumably there is a web application that is mapping the HTTP requests to the Jikan methods, etc.

**Comment by assintates** [comment]
Yep it's running of Dev branch (idk the version of the endpoint) it's running on Apache2 http server.

**Comment by assintates** [comment]
Just use the master branch it's latest if you see the graph in insights. 

https://github.com/jikan-me/jikan/network

**Comment by Fidelix** [comment]
I don't get it.
There isn't a file in the master branch (at least none that I could find) that will accept a request from an HTTP server and provide an HTTP response.

**Comment by assintates** [comment]
Hey bud welcome to the " I don't know php club" I was like you ATM when I first saw this API, you just have to wait for main dev or other guys who knows php.

**Comment by Fidelix** [comment]
@assintates I know PHP well enough.

The code in this repo simply isn't the same that is running on the hosted version.

**Comment by assintates** [comment]
I'll try to message @ifran aka main dev directly and make him see this issue quick that's all I can help with.

**Comment by irfan-dahir** [comment]
Hi @Fidelix, the REST API service is available here: https://github.com/jikan-me/jikan-rest/tree/development

Do note that I haven't made any means to  set up an in-depth tutorial for it. There are basic instructions to setting it up.

You'll need Apache, PHP7+, Composer and Redis.

**Comment by Fidelix** [comment]
Thanks @irfan-dahir ! This is exactly what I wanted :)
