### ISSUE TITLE
[Search] Manga list in character search is always empty

### ISSUE THREAD

**Issue by Ervie** [jikan-me/jikan#138]
I was developing jikan.net and during wrapping search request it struck me that every search result entry in character has empty "manga" key. Sometimes mangaography gets shifted to animeography of the character.

Example scenario: user call the following endpoint: https://api.jikan.moe/search/character/kirumi, which should be parse data from https://myanimelist.net/character.php?q=kirumi 

What one would expect: the only found character (Kirumi Tojo from "Danganronpa") has single element in "manga" array (as in MAL results).

What actually happens: said Kirumi has single element in "anime" array (the same one which is lacking from "manga array).

**Comment by irfan-dahir** [comment]
Good find! Working on a fix.
