### ISSUE TITLE
[Search] MAL redirect results in wrong id

### ISSUE THREAD

**Issue by Ervie** [jikan-me/jikan#139]
Yup, it's me again.

During searching person, if query is sufficiently clarified, MAL redirect to person profile instead of search result. Jikan handles such scenario, but parsed id is wrong.

Example scenario: user call the following endpoint: https://api.jikan.moe/search/person/sawashiro_miyuki, return data about Sawashiro Miyuki.

What one would expect: MAL Id key is correct and equals 99.

What actually happens: MAL id key equals 0.

**Comment by assintates** [comment]
Interesting.
