### ISSUE TITLE
Jikan without composer

### ISSUE THREAD

**Issue by fmohican** [jikan-me/jikan#140]
There its any way to use, without composer ?
I personally do not like to use "Composer". Can there be an alternative?

**Comment by irfan-dahir** [comment]
Jikan uses composer for autoloading via PSR4 and for easy package management. If you want to use Jikan without Composer, you'll have to create your own autoloader or require all the files.

Jikan does not have any dependencies, so you won't have to worry about recreating autoloaders for them.

Read more here: https://stackoverflow.com/a/40545971/2326811

Note: This will annoy you if a new version is released as you'll have to repeat the same process again. Highly recommend using composer! :)

**Comment by fmohican** [comment]
@irfan-dahir i just download, install and use get your package, but i get some errors
https://gist.github.com/fmohican/bc710abd90ac17927b43f83ff7543852
and also php cli : https://gist.github.com/fmohican/46ba5a2c1ebc40f129feccd46da8413e
"Tree /F" https://gist.github.com/fmohican/5d9302051476b8702eb0621295901469
the page content it's called `test.php`
```
<?php
require_once "vendor/autoload.php";
$jikan = new Jikan\Jikan;
$jikan->Anime(21);
var_dump($jikan->response);
?>
```
`https://wien.fmohican.ga/test.php`
```
PHP 7.2.3 (cli) (built: Feb 28 2018 05:48:02) ( NTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```
Webserver nginx

Can you tell me what i'm doing wrong?

**Comment by irfan-dahir** [comment]
Are you doing this with or without composer?


If it's without, then you don't need this line:
`require_once "vendor/autoload.php";`

And from the errors, you need to require `config.php`

**Comment by irfan-dahir** [comment]
If this is with composer, you need to initialize composer in your project directory.

**Comment by fmohican** [comment]
as I said I use composer.

**Comment by irfan-dahir** [comment]
Alright, please check above comment. I've edited it.

**Comment by fmohican** [comment]
Still same (or almost same) issues ....
https://gist.github.com/fmohican/d531c04f2289d9e9706515221572a748

Do you have some instant message (like discord,skype,etc) ?

**Comment by irfan-dahir** [comment]
Yep! That's it. That will create a `vendor` folder (`html\ws\vendor`). You will need to create a new file in `html\ws` e.g `index.php`

And then require `vendor/autoload.php` and instantiate a `new Jikan\Jikan` class from there.

Let me know if you have any issues

**Comment by irfan-dahir** [comment]
Sure, Nekomata#0428

**Comment by irfan-dahir** [comment]
Issue has been resolved. As per commit above.
