### ISSUE TITLE
Seasonals eats memory

### ISSUE THREAD

**Issue by coderiekelt** [jikan-me/jikan#143]
So whilst developing with the API, I encountered a small hurdle: the seasonal anime Get noms up about all available memory.

My current code:
`$animes = $jikan->Seasonal(strtolower($season->getSeason()), $season->getYear())->response;` 
Please do note that $season->getSeason() is always equal to an uppercased version of one of your constants.

The error message I'm getting is as follows:
`PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 262144 bytes) in <full file path>:<line no.> on line 0`

My development environment is as follows:
- PHP 7.2 on Windows 10
- php.ini set to allow 3 Gigabytes of memory to be consumed
- Symfony 4.0.9

**Comment by coderiekelt** [comment]
Nevermind, I did something very stupid.

**Comment by coderiekelt** [comment]
After much arguing from disgruntled co-workers and friends that found this issue.

The thing I did wrong was returning the getter that should've returned the Jikan instance.

```
function getJikan() {
return $this->getJikan();
}
```

Loop la Loop.

**Comment by irfan-dahir** [comment]
Haha, I was wondering how that happened.

Have you tried PHP profilers/debuggers? I personally use Xdebug+webgrind to evaluate performance issues with PHP scripts.
