### ISSUE TITLE
[Person] Add information about role.

### ISSUE THREAD

**Issue by Ervie** [jikan-me/jikan#146]
As promised ;)

Some responses from Jikan contain data about role level, i. e. if the character's role was main or supporting.

Example: little snippet from anime endpoint with Characters and Staff extension: https://imgur.com/wTLC3OE (with mentioned data underlined).

Idea for small extension: add this data to Person (and maybe Character?) endpoint. This data can be acquired from person profile on MyAnimeList: https://imgur.com/IxVaLLa.

This data could be added either on "character" (1) or "voice_acting_role" entry (2) level: <a href="https://imgur.com/bornOvR">related screen</a>

**Comment by irfan-dahir** [comment]
Okay, so;

- Addition of `role` from the character's endpoint for `animeography` and `mangaography`
As shown here: https://i.imgur.com/jGaXKhS.png

And hah! Looks like you've found another bug! The `role` parameters you highlighted is actually already returned. It's supposed to be this: https://i.imgur.com/hvRYknk.png

I'll issue a quick patch to add `role` for the characters' endpoint and fix the person's endpoint.

**Comment by Ervie** [comment]
Yeah, I noticed during implementing wrapper that every role was set to "character", but didn't question it much back then.

**Comment by irfan-dahir** [comment]
Yep, oddly this is quite an ancient bug given the parsing code is from the alpha days. ;)

Added and fixed!
e.g;
- http://api.jikan.moe/character/99
- http://api.jikan.moe/person/200

Allow 72~ hours for previous cache to expire.

**Comment by irfan-dahir** [comment]
Yep, oddly this is quite an ancient bug given the parsing code is from the alpha days. ;)

Added and fixed!
e.g;
- http://api.jikan.moe/character/99
- http://api.jikan.moe/person/200

Allow 72~ hours for previous cache to expire.

**Comment by assintates** [comment]
NIBBA WHY NOT PURGE CACHE. 


PS: check discord

**Comment by Ervie** [comment]
Nice. will make use of this feature next week :)

**Comment by irfan-dahir** [comment]
@assintates Unfortunately, I've badly coded the database part. :( Purging cache right now would mean resetting data, such as 
- https://api.jikan.moe/meta/status
- api.jikan.moe/meta/requests/anime/monthly

Gotta fix this in the next REST release.

**Comment by irfan-dahir** [comment]
@Ervie Great! Let me know if any more bugs/possible data inclusions pop up. You're quite good at finding them. :P
