### ISSUE TITLE
[Season] List of available seasons

### ISSUE THREAD

**Issue by IgorMCesar** [jikan-me/jikan#149]
Hi!
Is it possible to return all parameters avaible for all years, or just current year? I would like to make a selector based on year/season, but when a new season becomes avaible on the API it wont be possible to know, so i would have to add it manually everytime.

Example: 
GET (https://api.jikan.moe/season/) 
RESPONSE

`{
  "year": "2018",
  "seasons": [
    "fall": false,
    "summer": false,
    "spring": true,
    "winter": true
  ],
}`

Just an idea, dont know if it makes sense.
Thanks so much for all your work. Your API is saving me a lot of time, really. =)

**Comment by irfan-dahir** [comment]
Hey, glad it has been! This should be possible since MAL has a season archive. https://myanimelist.net/anime/season/archive
I'll what I can do.

**Comment by IgorMCesar** [comment]
So, i was rethinking this issue, sinse all the past data constant, i think the only info it is needed is whats the current season/year. From that simple info everyting else can be determined.
Maybe just https://api.jikan.moe/season/current) returning year and season would be enough.
What do you think?

Thanks again for all your work =)

**Comment by irfan-dahir** [comment]
You can get the current season's listings via https://api.jikan.moe/season; without specifying any extra parameters.

I can work on an endpoint that lists all the archived seasons with this sort of response
```json
{
  ...
  "2012": {"winter", "summer", "spring", "fall"},
  "2013": {"winter", "summer", "spring", "fall"}, 
  "2014": {"winter", "summer", "spring", "fall"},
  "2015": {"winter", "summer", "spring", "fall"}, 
  "2016": {"winter", "summer", "spring", "fall"},
  "2017": {"winter", "summer", "spring", "fall"},
  ...
}
```

**Comment by IgorMCesar** [comment]
Thats great, but the archived season list will never change its starting year, only its final year and season, The only info i think it lacks, as i said, is current season. There is no way atm to do so.  It would be needed to "guess" based on current date. An endpoint to specify whats the current season would be problematic to achieve?

**Comment by irfan-dahir** [comment]
Well, you'd always be able to access the last key in the JSON response since given it be the current season?

**Comment by IgorMCesar** [comment]
But wouldnt the last key be future seasons? If i am not mistaken MAL displays future seasons too.

**Comment by irfan-dahir** [comment]
Hmm, you may be right. I'll look into this and let you know

**Comment by irfan-dahir** [comment]
I've added two new keys to the `http://api.jikan.moe/season` endpoint: `season_name` and `season_year` which output the respective data for the current season.

Allow some time for the cache to expire if you can't view the keys for other seasons.

**Comment by IgorMCesar** [comment]
Thanks =D

**Comment by irfan-dahir** [comment]
added in v2
