### ISSUE TITLE
[Search] Handle slash in string query

### ISSUE THREAD

**Issue by Krarche** [jikan-me/jikan#152]
Hello,

Is there any way to use a query string that contains slash ? 
**Example** : https://api.jikan.moe/search/anime/Fate/Zero

If there isn't, would it be possible to handle them ?

**Comment by irfan-dahir** [comment]
Hi,

I would suggest URL Encoding the query like so: https://api.jikan.moe/search/anime/fate%2Fzero
But that is causing an issue, I'll look into it and see if I can have it allow encoded slashes.

Meanwhile, you could search by
- https://api.jikan.moe/search/anime/Fate%20Zero
- https://api.jikan.moe/search/anime/Fate+Zero

**Comment by irfan-dahir** [comment]
Upon further checking, it's not possible to allow slashes in the current URL structure. This is an issue that originates from the router, Lumen/Laravel, itself that I'm using for the REST API.
https://github.com/laravel/framework/issues/22125

Albeit, I've gone ahead and pushed a fix for this. You can request anything with slashes by URL/Percent Encoding by assigning a value to the `q` key in the URL.
- http://api.jikan.moe/search/anime/?q=Fate/Zero
- http://api.jikan.moe/search/anime/?q=Fate%2fZero

Note, this won't work by the default structure for pagination. So you'll have to use `page`.
- http://api.jikan.moe/search/anime/?q=Fate%2fZero&page=2

**Comment by Krarche** [comment]
Just tried, and it works perfectly ! Thank you for your very quick fix.

**Comment by irfan-dahir** [comment]
You're welcome!
