### ISSUE TITLE
[Anime|Manga] Return null for no synopsis

### ISSUE THREAD

**Issue by irfan-dahir** [jikan-me/jikan#153]
e.g  
- https://myanimelist.net/anime/37937/Wan_Jie_Xian_Zong
- https://myanimelist.net/manga/35545

**Comment by GregBaggings** [comment]
Instead of null, I would return a plain string as they do:
"No synopsis provided yet"

Returning null would be a wrong approach here, we could handle that at the API side.

**Comment by irfan-dahir** [comment]
This is what's currently returned when there's no synopsis/backround: https://api.jikan.moe/anime/37937

`No synopsis information has been added to this title. Help improve our database by adding a synopsis here.`

`null` would be the the correct approach here. Would allow client-side to serve their custom response by checking for null.
