### ISSUE TITLE
Characters & People aren't parsing!!1

### ISSUE THREAD

**Issue by irfan-dahir** [jikan-me/jikan#155]
Yes, I know. MAL is down for maintenance, Jikan REST only has cached data available. 

You'll be getting the `File not found` error for responses.

**Comment by coderiekelt** [comment]
Let's just hope they are not deploying some super duper update which screws over your templates.

**Comment by irfan-dahir** [comment]
Oh boi, I certainly hope not. That'd be a lot of work.

I'm betting them working on fixing whatever happened and getting their API back up.

**Comment by fmohican** [comment]
@irfan-dahir can you add support for `https://anidb.net/` ?

**Comment by irfan-dahir** [comment]
@fmohican AniDB already has an API: https://wiki.anidb.net/w/API

**Comment by irfan-dahir** [comment]
MAL's update on the issue:

```Dear Users,

The current maintenance period is a result of discovering a point in our security system that merited looking into further for any potential issues. Thus far, we have not found anything significant, but in the best interest of our users, and in an overabundance of caution, the maintenance period will continue until we have concluded our review. Having said that, we hope to have this matter resolved quickly, and will keep you apprised of when the site will be back online via MAL’s official site and social media accounts. We regret any inconveniences caused, and thank you for your patience and understanding.```

**Comment by fmohican** [comment]
@irfan-dahir yah, but you can implement as alternative to MAL

**Comment by irfan-dahir** [comment]
@fmohican I don't believe that's necessary. AniDB condemns scraping their site plus they already have an API that anyone can use. 

Jikan's purpose is to fulfill the lack of API MyAnimeList has.

**Comment by coderiekelt** [comment]
It would appear MyAnimeList is slowly coming back online, will report if any issues arise

**Comment by irfan-dahir** [comment]
Finally. The REST API seems to be working fine.

@coderiekelt Much appreciated, I'll have a look. Sorry, but could you also send the HTML source of the affected pages? Cuz again they're working fine on my end lol and I've no idea what to do to replicate the issue.

**Comment by coderiekelt** [comment]
Fetching anime information seems to have magically started working, however the seasonals are still a problem. In some digging I did, I found out that this only occurs with a German IP (for as far as I'm aware).

Here's the HTML as fetched by WGET (https://myanimelist.net/anime/season):
http://paste.ubuntu.com/p/gKSk98CzbK/

**Comment by irfan-dahir** [comment]
Sorry for the late response, will have a look at that today.

Update:
Manga
Manga search
Manga ranking (top, etc)

Endpoints are now working

**Comment by abhinavk99** [comment]
Character endpoint doesn't seem to work for me (I'm getting a `File does not exist` error with a `404` status code), but everything else does.

**Comment by irfan-dahir** [comment]
@abhinavk99 Yep, that and the people endpoint. Both still "under review" by MAL, hence down.

These stuff are just up for now: https://myanimelist.net/announcement/201806

**Comment by irfan-dahir** [comment]
I've created a Cachet page, you guys can check the status of the systems there.
Hover over the question mark icons for more info on endpoints that are not working.

https://status.jikan.moe

Also it seems Characters, People & Search for Characters/People are to be fixed within the week according to a tweet from MAL.

**Comment by irfan-dahir** [comment]
Jikan's 💯% functional again.

https://myanimelist.net/announcement/201806
