### ISSUE TITLE
Characters no longer working

### ISSUE THREAD

**Issue by qthen** [jikan-me/jikan#163]
Not sure if this is an issue with the hosted API, but the `characters` array is no longer populated when requesting `characters_staff` route. Normally when requesting this route, the property `character` is populated with the characters, their role, language, and their respective voice actors.

I think this is probably due to MAL changing their HTML format.

**Comment by Ervie** [comment]
Seconded, it seems few array properties return empty arrays now, as for `characters` in anime endpoint or `voice_acting_role` for person endpoint.

**Comment by irfan-dahir** [comment]
Sorry for the late fix! GitHub didn't send me any notification for this issue for some odd reason.

The affected parsers were:
- Anime's `characters`
- Manga's `characters`
- Person's `voice_acting_role`, `anime_staff_position`, `published_manga`

Allow upto 3 days for the old cache to expire on the REST API.
