### ISSUE TITLE
An incorrect and unused function in class Model/Model

### ISSUE THREAD

**Issue by tizis** [jikan-me/jikan#166]
![1](https://user-images.githubusercontent.com/16865573/42417001-2517a7ce-829f-11e8-95e1-16a495344fac.png)

Function "insert" is unused and have a bug:

```
    public function insert($class, $key_array, $value, $key = null)
    {
        if (property_exists('Jikan\Model\\'.$class, $key)) {
            if (is_null($key)) {
                $this->{$key_array}[] = $value;
            } else {
                $this->{$key_array}[$key] = $value;
            }
        }
    }
```
`if (property_exists('Jikan\Model\\'.$class, $key)) {` 
$key is element id in $key_array.

Solution: 

```
  public function insert($class, $key, $value, $key_array = null):void
  {
   if (property_exists('Jikan\Model\\'.$class, $key)) {
      if (null === $key_array) {
        $this->{$key}[] = $value;
      } else {
        $this->{$key}[$key_array] = $value;
      }
    }
  }
```

And why used `$class` and `'Jikan\Model\\'.$class,`  in function `property_exists`, this does not overcomplicate the code? It can be replaced by:

`(property_exists(\get_class($this), ...))`

**Comment by irfan-dahir** [comment]
Hey, you're right! That's pretty old code actually - from last year. I've removed the unused method - will add `(property_exists(\get_class($this), ...))` after a few tests.

We're currently working on a rewrite of the Jikan API. https://github.com/jikan-me/jikan/tree/2.0.0-dev

**Comment by tizis** [comment]
Ok, I just decided to improve my programming skills, so I started to disassemble the various libraries on GitHub, and I found this old code. 
I close the issue. Thanks for answer.

**Comment by irfan-dahir** [comment]
Thanks for finding that! :)

**Comment by tizis** [comment]
So, i noticed in v2.0.0 abstract model class with get/set functions was replaced with a single 'set' static function in model (like setProperties or fromParser) and 'get' function for each attribute (like getUrl or getTitle), why is it better than the previous solution?

I do not ask to waste time explaining to me, but would be grateful for a link to the article :)

**Comment by janvernieuwe** [comment]
Hi @tizis,

We're making a huge effort to use return types everywhere and make sure you can autocomplete anything that comes out of the lib in v2.
When using public properties we have no control over what users might put in it and possibly breaks the autocompletion.

Here is an article that talks about this and other good OOP practices that explains it a bit:
https://www.ibm.com/developerworks/opensource/library/os-php-7oohabits/index.html?ca=drs-tp4408
