### ISSUE TITLE
Undefined offset: 4

### ISSUE THREAD

**Issue by Nevermind23** [jikan-me/jikan#171]
```
 $this->addRule(
            'type',
            '~<span class="dark_text">Type:</span>~',
            function () {
                preg_match('~(<a href="(.*)">(.*?)</a>|(.*))</div>~', $this->file[$this->lineNo + 1], $this->matches);
                $this->model->set('Anime', 'type', (empty($this->matches[3]) ? $this->matches[4] : $this->matches[3]));
            }
        );
```

$jikan->response returns: Undefined offset: 4

**Comment by irfan-dahir** [comment]
@Nevermind23 I can't seem to reproduce the issue, which Anime ID are you parsing?

**Comment by Nevermind23** [comment]
Here is screen of error: https://i.imgur.com/EhGFk7N.png
I am using latest version of laravel

My code:
`use Jikan\Jikan;

class Fetcher extends Controller
{
    public function fetch()
    {
        $fetch = new Jikan();
        $fetch->Anime(21);
        return $fetch->response;
    }
}`

**Comment by irfan-dahir** [comment]
I've tested the code both on linux and windows and it works fine on my end albeit I do have a clue as to what this may be.

Could you dump the source of this page from your end: https://myanimelist.net/anime/21 and drop me a link to it here?
It must be from where you're executing your application which is throwing that error.

**Comment by Nevermind23** [comment]
MAL source: https://justpaste.it/4ahj7

**Comment by irfan-dahir** [comment]
Oddly, given the HTML, it should be parsing. I've reviewed the code either way, can you test out `dev-master` and let me know if this patch works for you?

**Comment by irfan-dahir** [comment]
Hi, if you're still facing the issue. Update to v2.

Docs available here: http://docs.jikan.moe
