### ISSUE TITLE
api.jikan.moe : Undefined Offset When Request Top Anime from

### ISSUE THREAD

**Issue by aldesy** [jikan-me/jikan#172]
Everytime i request this https://api.jikan.moe/top/anime/1
i always got this response
{"error":"Undefined offset: 1914"}
need to refresh until 5-10 times to get the success response.
please help

**Comment by irfan-dahir** [comment]
Hi, one of our load balancers was having trouble parsing, an issue related to #148, whereas the other one was parsing with no problems.

The problem has been fixed, should work now. :ok_hand:
