### ISSUE TITLE
Error in name

### ISSUE THREAD

**Issue by IDerr** [jikan-me/jikan#175]
Hello :D
Jikan reports Black Lagoon: Roberta's Blood Trail [this](https://myanimelist.net/anime/4901/Black_Lagoon__Robertas_Blood_Trail?q="Black%20Lagoon%3A%20Roberta)
with this title : "Black Lagoon: Roberta& #039;s Blood Trail"

Should we decode all HTML-code or is it an error in the back-end?

Thanks a lot :D

**Comment by IDerr** [comment]
I don't really know, I am using the api.jikan.moe
So it should be :
JikanREST: "2.2",
JikanPHP: "1.16.2"

**Comment by irfan-dahir** [comment]
Hi, that's an issue with the current parser. Will be fixed in the next REST update (~end of this month) for all responses.

You'll have to HTML decode the responses for now

**Comment by IDerr** [comment]
ok thx
