### ISSUE TITLE
cURL error 7

### ISSUE THREAD

**Issue by KarimQaderi** [jikan-me/jikan#176]
Hello, I'm having a problem, can you fix my problem

![image](https://user-images.githubusercontent.com/32425175/43992520-9e4d043a-9d94-11e8-9eef-a58e71f18ace.png)

```
cURL error 7: Failed to connect to myanimelist.net port 443: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

**Comment by irfan-dahir** [comment]
Hi @KarimQaderi, are you using any sort of proxy?
Try visiting https://myanimelist.net/anime/1 via your browser and see if that works

**Comment by KarimQaderi** [comment]
https://myanimelist.net/
You are in our country filtered

I use proxy

**Comment by irfan-dahir** [comment]
Okay, please note that MyAnimeList blocks a range of VPNs/Proxy so use one that's not blocked by them.

You can inject a separate GuzzleHttp Client with the proxy details. Below is a proxy that I've tested that works, just replace it with whichever you're using.
```
$client = new GuzzleHttp\Client([
	'proxy' => 'http://139.255.57.32:8080'
]);

$jikan = new Jikan\Jikan($client);
$anime = $jikan->Anime(1);
```

Let me know if this works for you.

**Comment by KarimQaderi** [comment]
Thank you, my problem was solved
