### ISSUE TITLE
Searching a short name anime failed

### ISSUE THREAD

**Issue by IDerr** [jikan-me/jikan#179]
Hi :D 
When searching the anime K : [](https://myanimelist.net/anime/14467/K?q=K ), jikan return 0 results : 

[Screenshot](https://i.imgur.com/sWFDS1E.png)
[Screenshot from MAL search](https://i.imgur.com/uI6Vwda.png)

Thanks a lot :D

**Comment by janvernieuwe** [comment]
Hi, we're using this page https://myanimelist.net/anime.php?q=k
As you can see you need at least 3 characters.
