### ISSUE TITLE
[Person] Does not parse manga, anime, voice acting

### ISSUE THREAD

**Issue by Ervie** [jikan-me/jikan#180]
MAL probably changed something within page source again, as `Person` endpoint return empty arrays for `voice_acting_role`, `anime_staff_position`, `published_manga`.

**Comment by Ervie** [comment]
Oh, BTW, same thing happens with `Anime` endpoint with `characters_staff` extension (empty `character` string). Might be related to changes done in issue #163?

**Comment by irfan-dahir** [comment]
Updated the parser. Allow a max of 3 days for the older cache to expire.
