### ISSUE TITLE
[Manga] getTitleEnglish() must be of the type string, null returned

### ISSUE THREAD

**Issue by Kaishiyoku** [jikan-me/jikan#181]
https://jikan-me.github.io/jikan-docs/objects/model/manga/manga/#gettitleenglish-string

When `Jikan\Model\Manga\Manga::getTitleEnglish()` returns a null value, an exception is being raised because a string is expected:

```php
 Symfony\Component\Debug\Exception\FatalThrowableError  : Return value of Jikan\Model\Manga\Manga::getTitleEnglish() must be of the type string, null returned

```

**Comment by janvernieuwe** [comment]
Hi @Kaishiyoku ,

Thanks for checking out the new version.
I pushed a fix so that null values are allowed here, check out dev-master for the fix.
