### ISSUE TITLE
add trailer video

### ISSUE THREAD

**Issue by KarimQaderi** [jikan-me/jikan#185]
Please add this part

![image](https://user-images.githubusercontent.com/32425175/44341985-ddeec180-a49e-11e8-9741-c6050c58bde9.png)

**Comment by janvernieuwe** [comment]
Hi @KarimQaderi ,

The new parser already supports this as `getPreviewVideoUrl` on the anime model.
The rest api should get this in v3 soon when it is released.

Should maybe rename it to `getTrailer` though :)

**Comment by KarimQaderi** [comment]
tnx

**Comment by irfan-dahir** [comment]
Added! Key is `trailer_url`
