### ISSUE TITLE
/search/{type}/{query} endpoint returns error in v3

### ISSUE THREAD

**Issue by steffantucker** [jikan-me/jikan#190]
`https://api.jikan.moe/v3/search/manga/Grand%20Blue` returns `error: "Invalid or incomplete endpoint"`, even on the 'Search request example + schema' on the apiary.io docs. 
`https://api.jikan.moe/v2/search/manga/Grand%20Blue` still works, as does `https://api.jikan.moe/v3/search/manga?q=Grand%20Blue`

**Comment by irfan-dahir** [comment]
Hi, the former method for querying in v2 is depreciated in v3. You are encouraged to pass queries in `q={query}`

Reasons for this being
- Support of backslashes `/`
- Complete percentage encoding
- Fetches accurate data from MAL

Forgot to mention this in the REST documentation, will fix it!
