### ISSUE TITLE
parseDate returns the current date when given M, Y

### ISSUE THREAD

**Issue by miraris** [jikan-me/jikan#192]
There's a bug [here](https://github.com/jikan-me/jikan/blob/master/src/Helper/Parser.php#L79) - 
When parseDate is given a string in the format `Jan, 2019`, it just plugs it into the `\DateTimeImmutable` constructor, which doesn't recognize that format.
A quick fix would be to add another condition:
```php
if (preg_match('/(\w{3}), (\d{4})/', $date, $matches)) {
    return \DateTimeImmutable::createFromFormat('M d, Y', "{$matches[1]} 01, {$matches[2]}", new \DateTimeZone('UTC'));
}
```

A better alternative (imo) would be to parse the date into an object with nullable properties:
```json
{
  "year": 2019,
  "month": 1,
  "day": null
}
```
This lets the client choose whether to make this a full `Date` data type (by replacing the nulls with 01) or use the MAL's format.

**Comment by miraris** [comment]
Another alternative is simply adding `fromPrecision` & `toPrecision` which specifies the precision of the date (day, month, year).

**Comment by irfan-dahir** [comment]
Since the main issue is within the `DateRange` class, I've gone ahead and added a `DateProp` class (for nullable props) which returns with the following `DateRange` methods; `getFromProp` & `getUntilProp`

Like so `$anime->getAired()->getFromProp()->getDay();`

As for the solution for the active issue i.e `parseDate` returning incorrect value, should be this IMO
```
if (preg_match('/(\w{3}), (\d{4})/', $date, $matches)) {
    return \DateTimeImmutable::createFromFormat('M d, Y', "{$matches[1]} 01, {$matches[2]}", new \DateTimeZone('UTC'));
}
```
I'm not sure where `fromPrecision` and `toPrecision` would be plugged in though.

**Comment by irfan-dahir** [comment]
Okay, done. That should fix it. With the nullable props added too, I don't think we'll need `fromPrecision`/`toPrecision`.

Here's what they look together for fetching the latter date.
![screenshot from 2018-09-25 08-59-23](https://user-images.githubusercontent.com/9166451/45992210-f3f53080-c0a1-11e8-988e-941e2ac3b326.png)
DateProps returns a `null` for day where-as for `parseDate`, the `01` is appended for day (which should fix the issue in the REST service)
