### ISSUE TITLE
replace autumn to fall

### ISSUE THREAD

**Issue by KarimQaderi** [jikan-me/jikan#197]
![image](https://user-images.githubusercontent.com/32425175/45679987-0b3a9800-bb4f-11e8-900e-c5049b5ad8f8.png)

![image](https://user-images.githubusercontent.com/32425175/45680060-39b87300-bb4f-11e8-83a5-1bbd5afc042b.png)

**Comment by irfan-dahir** [comment]
Update to `dev-master`, this issue has been resolved.

https://github.com/jikan-me/jikan/blob/758d0802787ba41e78a78a899502eeac429253ba/src/Request/Seasonal/SeasonalRequest.php#L34
