### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by KyuBlade** [jikan-me/jikan#198]
Requesting this route give a server error without any details.

https://api.jikan.moe/v3/anime/11757

**Comment by irfan-dahir** [comment]
Was a parser related issue. MAL likes to throw around empty links (`<a href="/anime//"></a>`) in the related section when there's no relation items. :thinking: 
![screenshot from 2018-09-19 22-15-01](https://user-images.githubusercontent.com/9166451/45769785-10d0d480-bc5a-11e8-8ab1-2bd0fafd04aa.png)

Works now. :+1:  https://api.jikan.moe/v3/anime/11757
