### ISSUE TITLE
Issues while hitting the profile endpoint in apiary

### ISSUE THREAD

**Issue by anshumanv** [jikan-me/jikan#208]
Can you try hitting the profile endpoint from apiary? Seems to work normally in browser but not in the docs.

![screenshot from 2018-11-26 20-18-29](https://user-images.githubusercontent.com/21009455/49021380-7e4c3480-f1b8-11e8-80bc-242076526a37.png)

**Comment by irfan-dahir** [comment]
Hi, sorry for the late response.

It seems Apiary keeps adding that `/anime` param at the end of the URL even if it's ticked off.
`https://private-amnesiac-b6a8c-jikan.apiary-proxy.com/v3/user/Nekomata1037/profile/anime`

I'm not sure why it is doing this, will look into it.

**Comment by anshumanv** [comment]
Sure thanks, closing this as this seems to be an issue in apiary. :+1:
