### ISSUE TITLE
Rating scores disagree when some rating values have zero votes

### ISSUE THREAD

**Issue by mwalimu59** [jikan-me/jikan#216]
If an anime or manga has been rated few enough times that some of the rating values have zero votes, the scores array returned by a stats request differ from those displayed on MAL.

For example, compare the following:
https://myanimelist.net/anime/34340/Hikoichi_Tonchi_Banashi/stats
https://api.jikan.moe/v3/anime/34340/stats
As of 3/20/2019 the MAL page shows rows for 10, 8, 6, 5, 4, 2, 1 whereas the scores array in the JSON data returned by Jikan has entries for 10, 9, 8, 7, 6, 5, 4 with votes matching according to the relative position (when compared as shown here; the JSON is actually in reverse order).

The same problem occurs with manga where some of the score values have zero votes.

**Comment by irfan-dahir** [comment]
Thank you for reporting this! Will look into it.

**Comment by irfan-dahir** [comment]
Sorry this took so long, the issue has been resolved.
