### ISSUE TITLE
No support for POST

### ISSUE THREAD

**Issue by mlindner** [jikan-me/jikan#219]
This API is rather non-functional without support for POST, that is editing MAL user lists. Please add this.

**Comment by sbrecken** [comment]
> Notice: Jikan does not support authenticated requests. You can not update your lists.

There is no public API currently that supports updating user lists, so its not that easy to do so. You can look at [jikan-auth](https://github.com/jikan-me/jikan-auth) to see why.

**Comment by irfan-dahir** [comment]
Hi, please use this: https://github.com/jikan-me/jikan-auth

If you're talking about the REST API, it's not possible due to [limitation](https://github.com/jikan-me/jikan-auth#reasons)

**Comment by mlindner** [comment]
You should be able to implement it via scraping.

**Comment by mlindner** [comment]
jikan-auth doesn't work for me because of the PHP requirement. I don't know or use PHP. I would need a Python API, ideally.

**Comment by irfan-dahir** [comment]
See my comment above regarding the limitations. 
Furthermore it's a security risk, would you send your or your users' MyAnimeList credentials to a third party REST API?

Your solution would be implementing a client-side solution by authenticate through the login page and use the session data to send further requests to MAL for managing lists via their JSON API.

**Comment by purplepinapples** [comment]
I find it incredibly finicky to deal with the CSRF token, so I've typically done something like this with python and selenium in the past if I want to edit lists programmatically. The following code was used to edit my tags on MyAnimeList

```python
#!/usr/bin/env python3

from selenium import webdriver
from downloadMALList import downloadList

from time import sleep
from os import path
import sys

def editTags(orig_tags, status):
    if orig_tags is None:
        orig_tags = ""
    tags = list(map(lambda x: x.strip(), [tag for tag in orig_tags.replace("\n", "").split(",") if tag.strip()]))
    if status == '6':
        if 'normal priority' not in tags:
            tags.append('normal priority')
    return tags


def checkForDropDown(driver):
    try:
        driver.find_element_by_id('show-advanced-button').click();
    except:
        pass
    return

def edit_entry(driver, item_id, fixed_tags):
    try: 
        driver.get('https://myanimelist.net/editlist.php?type=anime&id={}'.format(item_id))
        checkForDropDown(driver)
        driver.find_element_by_id('add_anime_tags').click()
        driver.find_element_by_id('add_anime_tags').clear()
        driver.find_element_by_id('add_anime_tags').send_keys(fixed_tags)
        sleep(5)
        driver.find_element_by_css_selector('#top-submit-buttons>.inputButton.main_submit').click()
        return True
    except:
        return False

def main():

    username = "purplepinapples"
    list_of_entries = downloadList(username)
    
    errors = {}
    
    for entry in list_of_entries:
        current_id = entry['series_animedb_id']
        original_tags = entry['my_tags']
        status = entry['my_status']
        new_tags = ', '.join(editTags(original_tags, status))
        if (new_tags != original_tags):
            errors[current_id] = new_tags

    driver = webdriver.Chrome()
    input("Log in Now")
    keys = list(errors.keys())
    print(keys)
    while len(errors) > 0:
        key = keys[0]
        print(key)
        suceeded = edit_entry(driver, key, errors[key])
        if suceeded:
            del errors[keys.pop(0)] # remove from keys list and delete
    driver.quit()

if __name__ == "__main__":
    main()
```

The `downloadList` function used the `malappinfo` endpoint when that was still a thing, but it could be replaced by `load.json` requests, see [here](https://github.com/jikan-me/jikan/issues/217#issuecomment-478302800) for an example.

**Comment by irfan-dahir** [comment]
In addition, [here's a specification for MAL's JSON API](https://github.com/jikan-me/jikan-auth/blob/master/SPECIFICATION.md).

As for adding POST support, I'm sorry but it's out of scope for the API. I hope the solutions above work for you.
