### ISSUE TITLE
Related anime doesn't show the correct type

### ISSUE THREAD

**Issue by xyzwilliamxyz** [jikan-me/jikan#225]
Hi,

I'm not entirely sure if it's a bug or more of a feature request. I was planning on making an app that shows related stuff to the anime like movies, ONAs, specials and so on.

I checked the anime API, it returns the related animes as I'd like it to, however it only has 2 types **anime** or **manga**, not taking into consideration the other existing types of anime. Well, for my app I could simply make the other requests to **anime** API for each item to get the data I need, however it's going to take some time. So I think it'd be nicer if the API already returned this data.

But on the other hand, I wonder whether or not it's going to add an overhead to the anime API, because technically it'd have to make all these extra scrapping to other pages in order get this info. So I ask, would it be fine to add this feature?

**Comment by janvernieuwe** [comment]
We're only showing the data that is available on the page.
Manga and anime we can detect from the URL's.

It's very unlikely we'll ever support this.

**Comment by purplepinapples** [comment]
To elaborate, heres all the information on the page for an anime entry

```html
<tbody><tr><td class="ar fw-n borderClass" valign="top" nowrap="">Adaptation:</td><td class="borderClass" width="100%"><a href="/manga/173/Cowboy_Bebop">Cowboy Bebop</a><br><a href="/manga/174/Shooting_Star_Bebop__Cowboy_Bebop">Shooting Star Bebop: Cowboy Bebop</a></td></tr><tr><td class="ar fw-n borderClass" valign="top" nowrap="">Side story:</td><td class="borderClass" width="100%"><a href="/anime/17205/Cowboy_Bebop__Ein_no_Natsuyasumi">Cowboy Bebop: Ein no Natsuyasumi</a><br><a href="/anime/5/Cowboy_Bebop__Tengoku_no_Tobira">Cowboy Bebop: Tengoku no Tobira</a></td></tr><tr><td class="ar fw-n borderClass" valign="top" nowrap="">Summary:</td><td class="borderClass" width="100%"><a href="/anime/4037/Cowboy_Bebop__Yose_Atsume_Blues">Cowboy Bebop: Yose Atsume Blues</a></td></tr></tbody>
```

If the parser was to include additional information, it would be doing additional requests each time someone requested something on the `anime` endpoint.

If someone was to request something from Gundam or DBZ, that would do over 20 extra requests, when the user may not have wanted that.

> Well, for my app I could simply make the other requests to anime API for each item to get the data I need

this seems like the most reasonable solution

**Comment by xyzwilliamxyz** [comment]
Thanks for the reply guys, so I'll stick to deal with it on the app
