### ISSUE TITLE
[HOSTED] Generated Issue: ParserException

### ISSUE THREAD

**Issue by gianlucamachado** [jikan-me/jikan#227]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```v2.8.1@75c3fd2230133b01175b95ec5397aa66d60ba1f8```
**PHP:** ```7.3.5-1+ubuntu18.04.1+deb.sury.org+1```
**Redis**: ```Connected```
**Exception:** ```Jikan\Exception\ParserException```
**Code:** ```0```
**Message:** ```Failed to parse 'https://myanimelist.net/people.php?q=a'```
**Trace:** ```/var/www/jikan-rest/vendor/jikan-me/jikan/src/Exception/ParserException.php on line 24```
**Request:** `GET /v3/search/people?q=a&limit=3`

**Comment by purplepinapples** [comment]
Your query has to have a minimum of 3 letters.

See [here](https://jikan.docs.apiary.io/#reference/0/search):

> NOTE: MyAnimeList only processes queries with a minimum of 3 letters

If you visit https://myanimelist.net/people.php?q=a (the link from the error message), you'll see the same error:


> There were some probrems:
> Must have at least 3 byte characters to search

**Comment by irfan-dahir** [comment]
In addition to above, it's not a parser issue as the error message states `Failed to parse 'https://myanimelist.net/people.php?q=a'`.

Will have the API return Bad Request (HTTP 400) instead. Leaving the issue open until that patch is added.

**Comment by irfan-dahir** [comment]
Added `BadResponseException` if query is present and query size is < 3
