### ISSUE TITLE
[HOSTED] Generated Issue: ParserException

### ISSUE THREAD

**Issue by barkdoll** [jikan-me/jikan#228]
Please fill out the details below.

**Summary:**
Navigating to the following url returns a 500 status.
```
https://api.jikan.moe/v3/anime/322/episodes/1
```

**Steps to reproduce:**
1. Run `curl` on or navigate to https://api.jikan.moe/v3/anime/322/episodes/1 in a browser.

That's it. You will see the error message. It told me to report it here. Hope this helps!

 ### Additional Details 
 **Jikan Parser Version**: ```v2.8.1@75c3fd2230133b01175b95ec5397aa66d60ba1f8```
**PHP:** ```7.3.5-1+ubuntu18.04.1+deb.sury.org+1```
**Redis**: ```Connected```
**Exception:** ```Jikan\Exception\ParserException```
**Code:** ```0```
**Message:** ```Failed to parse 'https://myanimelist.net/anime/322/_/episode?offset=0'```
**Trace:** ```/var/www/jikan-rest/vendor/jikan-me/jikan/src/Exception/ParserException.php on line 24```
**Request:** `GET /v3/anime/322/episodes/1`

**Comment by irfan-dahir** [comment]
Thanks for reporting! The issue has been resolved
