### ISSUE TITLE
Bug: https://api.jikan.moe/v3/season/2018/winter doesn't work

### ISSUE THREAD

**Issue by MarchWorks** [jikan-me/jikan#230]
I haven't tested in the other routes but this one is used in my app and it return `500 (Internal Server Error)`. 
Most likely this isn't an error in the code.

**Comment by MarchWorks** [comment]
Working now

**Comment by janvernieuwe** [comment]
Hi, there is a server issue that Nekomata is looking at right now.
Sorry for the inconvinience, we're getting things up and running again asap.

**Comment by MarchWorks** [comment]
That's why serverless is good if I am not mistaken

**Comment by irfan-dahir** [comment]
Hi, there's an issue with our servers which has affected all endpoints. The service is currently back up as we've shifted to a temporary solution until we get the issue resolved.

More details on our discord channel:  https://discord.gg/4tvCr36

**Comment by MarchWorks** [comment]
Thanks for your work
