### ISSUE TITLE
fetching characters_staff only returns the list of staff

### ISSUE THREAD

**Issue by Moralde-Sama** [jikan-me/jikan#236]
this request 

> https://api.jikan.moe/v3/anime/37744/characters_staff/

![image](https://user-images.githubusercontent.com/41711381/63220405-73f41f80-c1b9-11e9-901e-7c896fccf995.png)
only returns the list of staff but it should return the list of characters since It is exist in myanimelist

> https://myanimelist.net/anime/37744/Isekai_Cheat_Magician

![image](https://user-images.githubusercontent.com/41711381/63220415-88d0b300-c1b9-11e9-8eaf-384419a85246.png)

**Comment by seanbreckenridge** [comment]
FYI,

while hosting this locally, I get the information fine.

I can confirm it wasnt working yesterday at api.jikan.moe, there were some caching issues fixed today but not sure if it would have affected this.

```

❯ curl localhost:8000/v3/anime/37744/characters_staff/
{"request_hash":"request:anime:386a0a3199d1455034a66335cc1c7f4775056f7a","request_cached":true,"request_cache_expiry":86369,"characters":[{"mal_id":171669,"url":"https:\/\/myanimelist.net\/character\/171669\/Rin_Azuma","image_url":"https:\/\/cdn.myanimelist.net\/images\/characters\/13\/383968.jpg?s=43ddd039f476583e66f8db67450e589a","name":"Azuma, Rin","role":"Main","voice_actors":[{"mal_id":34785,"name":"Takahashi, Rie","url":"https:\/\/myanimelist.net\/people\/34785\/Rie_Takahashi","image_url":"https:\/\/cdn.myanimelist.net\/r\/23x32\/images\/voiceactors\/1\/48142.jpg?s=104a9954420069bf9342222151034ab7","language":"Japanese"}]},{"mal_id":171668,"url":"https:\/\/myanimelist.net\/character\/171668\/Taichi_Nishimura","image_url":"https:\/\/cdn.myanimelist.net\/images\/characters\/5\/383966.jpg?s=a9c1ebd90e081def92eb994744f29700","name":"Nishimura, Taichi","role":"Main","voice_actors":[{"mal_id":38438,"name":"Amasaki, Kouhei","url":"https:\/\/myanimelist.net\/people\/38438\/Kouhei_Amasaki","image_url":"https:\/\/cdn.myanimelist.net\/r\/23x32\/images\/voiceactors\/1\/53622.jpg?s=131189db78878c0bf8e7811df54c41fd","language":"Japanese"}]}

```

Jikan is currently being rate limited pretty heavily, so I can't check the remote endpoint.

**Comment by seanbreckenridge** [comment]
~7500 seconds (2 hrs) TTL on the request above on api.jikan.moe, should hopefully fix there after its re-requested

**Comment by Moralde-Sama** [comment]
I can now fetched the characters, I'll close this for now
