### ISSUE TITLE
Is there a data dump available for download?

### ISSUE THREAD

**Issue by RedRain77** [jikan-me/jikan#237]
Is there a data dump available for download?
That includes all of the data scraped by Jikan.

**Comment by seanbreckenridge** [comment]
No, pages are only requested/parsed when requested from MAL, and gets re-requested if they another request is sent to an endpoint after it expires [(which depends o the endpoint)](https://github.com/jikan-me/jikan-rest/blob/master/.env.dist#L18). Jikan doesn't go out of its way to request every page on MAL, even with all the worker servers currently in use it wouldn't be easy to constantly have every page cached and up to date.

Storing the data for longer than that and simply having a dump of all the data would also be against [MALs TOS](https://myanimelist.net/membership/terms_of_use)
