### ISSUE TITLE
502 Bad Gateway on all requests

### ISSUE THREAD

**Issue by J-Puls** [jikan-me/jikan#242]
Server is responding with 502 Bad Gateway on all requests.
Started around 4pm EST (1/8/2020).

**Comment by Takaitech** [comment]
Just ran into this as well,
The only request I'm not getting 502 Bad Gateway seems to be for top anime by popularity
https://api.jikan.moe/v3/top/anime/1/bypopularity

**Comment by irfan-dahir** [comment]
The issue has been resolved, thanks for reporting. Please re-open this issue if you face the problem again.
