### ISSUE TITLE
Uncaught TypeError in AnimeParser when Rank is N/A

### ISSUE THREAD

**Issue by Gargadon** [jikan-me/jikan#249]
**Summary:** When anime is ranked as N/A, Jikan\Parser\Anime\AnimeParser::getRank() returns a string instead of null.

**Steps to reproduce:** Fetch any anime which its rank is N/A, e.g. https://myanimelist.net/anime/40262/Haikyuu__Riku_vs_Kuu

**Error message:**
`Fatal error: Uncaught TypeError: Return value of Jikan\Parser\Anime\AnimeParser::getRank() must be of the type integer or null, string returned in /home/gargadon/gargadon.info/vendor/jikan-me/jikan/src/Parser/Anime/AnimeParser.php:464 Stack trace: #0 /home/gargadon/gargadon.info/vendor/jikan-me/jikan/src/Model/Anime/Anime.php(219): Jikan\Parser\Anime\AnimeParser->getRank() #1 /home/gargadon/gargadon.info/vendor/jikan-me/jikan/src/Parser/Anime/AnimeParser.php(43): Jikan\Model\Anime\Anime::fromParser(Object(Jikan\Parser\Anime\AnimeParser)) #2 /home/gargadon/gargadon.info/vendor/jikan-me/jikan/src/MyAnimeList/MalClient.php(59): Jikan\Parser\Anime\AnimeParser->getModel() #3 /home/gargadon/gargadon.info/vendor/jikan-me/jikan/src/Jikan.php(52): Jikan\MyAnimeList\MalClient->getAnime(Object(Jikan\Request\Anime\AnimeRequest)) #4 /home/gargadon/gargadon.info/prueba.php(9): Jikan\Jikan->Anime(40262) #5 {main} thrown in /home/gargadon/gargadon.info/vendor/jikan-me/jikan/src/Parser/Anime/AnimeParser.php on line 464`

**Comment by janvernieuwe** [comment]
I tried to reproduce this on Saturday, but unfortunately it had a rank by then.
If you encounter this issue again, it could be helpful to provide a failing test with php-vcr recording if possible.

**Comment by irfan-dahir** [comment]
Managed to find one with a 'N/A' rank. I've pushed a fix which I'll publish in the next release but you can update directly to the commit referenced above @Gargadon

**Comment by Gargadon** [comment]
@irfan-dahir Tested with https://myanimelist.net/anime/41062/Tomica_Kizuna_Gattai__Earth_Granner, now it works well.

Thank you.
