### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by anehmee** [jikan-me/jikan#268]
**Summary:**
Error :  Return value of Jikan\\Parser\\Anime\\AnimeParser::getScoredBy() must be of the type int or null, string returned

trace: /var/www/jikan/vendor/jikan-me/jikan/src/Parser/Anime/AnimeParser.php at line 428

**Steps to reproduce:**
Calling https://api.jikan.moe/v3/anime/40028

 ### Additional Details 
status | 500
type | "Exception"
message | "Unhandled Exception. Please follow report_url to generate an issue on GitHub"
trace | "/var/www/jikan/vendor/jikan-me/jikan/src/Parser/Anime/AnimeParser.php at line 428"
error | "Return value of Jikan\\Parser\\Anime\\AnimeParser::getScoredBy() must be of the type int or null, string returned"

**Comment by irfan-dahir** [comment]
@seanbreckenridge That was indeed the case, thank you!
