### ISSUE TITLE
api gives wrong last_page info when search by "genre"

### ISSUE THREAD

**Issue by carmitvinik** [jikan-me/jikan#273]
hi
i ve tried to search only shounen animeList by this:
https://api.jikan.moe/v3/search/anime?genre=27

the json property of last_page says there is only one page while actually it is supposed to be 39
with result of 45 items in last page.

i can manage myself but it is a bug that should be fixed.
thnx
carmit vinik 27 . 3 . 2020

**Comment by irfan-dahir** [comment]
Issue is similar to #261 
A fix will be out in the next major version

**Comment by irfan-dahir** [comment]
[Resolved in v4.](https://github.com/jikan-me/jikan/issues/261#issuecomment-1043740368)
