### ISSUE TITLE
Mean score value type was changed

### ISSUE THREAD

**Issue by slash2020327** [jikan-me/jikan#274]
I'm getting exception below when I tried to get a user.
 
### Additional Details 
 **Jikan Parser Version**: ```v2.16.2@4e3781e1617047921d20acc7bb4390bc8e83502d```
**PHP:** ```7.3.13-1+ubuntu18.04.1+deb.sury.org+1```
**Redis**: ```Connected```
**Exception:** ```Symfony\Component\Debug\Exception\FatalThrowableError```
**Code:** ```0```
**Message:** ```Return value of Jikan\Parser\User\Profile\AnimeStatsParser::getMeanScore() must be of the type float or null, string returned```
**Trace:** ```/var/www/jikan/vendor/jikan-me/jikan/src/Parser/User/Profile/AnimeStatsParser.php on line 73```
**Request:** `GET /v3/user/Slashnyan`

**Comment by irfan-dahir** [comment]
Thanks for opening an issue. It's now resolved.

http://api.jikan.moe/v3/user/Slashnyan
