### ISSUE TITLE
mal_id for 'staff' on club endpoint always return 0

### ISSUE THREAD

**Issue by seanbreckenridge** [jikan-me/jikan#279]
[Reported by Ganen on the discord](https://discordapp.com/channels/460491088004907029/475889826852503554/698479604230520852):

https://api.jikan.moe/v3/club/72940

<img src="https://cdn.discordapp.com/attachments/475889826852503554/698480260211146782/unknown.png">

https://github.com/jikan-me/jikan/blob/master/src/Model/Club/Club.php#L179-L185
https://github.com/jikan-me/jikan/blob/master/src/Parser/Club/ClubParser.php#L255-L291 never parses a MAL ID
I think this is because in `Club.php` its defined as a `MalUrl[]`, instead of Model specific to a club user:
https://github.com/jikan-me/jikan/blob/master/src/Model/Common/MalUrl.php
and https://github.com/jikan-me/jikan/tree/master/src/Parser/Common/MalUrlParser.php
which that defaults to 0
```
<div class="borderClass"><a href="/profile/daya">daya</a> (Admin)</div>
```
no way to parse the user id for someone from the information on the club page
so, I think some new model specific to a club user should probably be changed to remove the mal_id field in v4

**Comment by irfan-dahir** [comment]
Fixed in [REST v4](https://api.jikan.moe/v4/clubs/72940/staff) and referenced commit above
