### ISSUE TITLE
[Search] BadResponseException (HTTP 403, 500, etc)

### ISSUE THREAD

**Issue by AhmadKahlid** [jikan-me/jikan#283]
https://api.jikan.moe/v3/search/anime?q=naruto%20shippuuden&page=1
``` json
{
  "status": 403,
  "type": "BadResponseException",
  "message": "Something went wrong, please try again later",
  "error": "403 on https://myanimelist.net/anime.php?q=naruto+shippuuden&type=0&score=0&status=0&p=0&r=0&sd=0&sm=0&sy=0&ed=0&em=0&ey=0&gx=0&c[]=a&c[]=b&c[]=c&c[]=f&c[]=d&c[]=e&c[]=g"
}
```

**Comment by irfan-dahir** [comment]
![image](https://user-images.githubusercontent.com/9166451/82585779-080f6f00-9bb0-11ea-9aa4-8006d73c175d.png)

MAL is has been unstable the past few hours. Has been returning either 403, 502, 504, etc
https://www.isitdownrightnow.com/myanimelist.net.html

**Comment by izay4kun** [comment]
It really is unstable for the past few hours, but the 403 error may be a security measure against API's in general, a simple curl on your local machine would return the page data. But from a dedicated server/vps it will throw 403 forbidden (even setting UA, referer etc.).

**Comment by irfan-dahir** [comment]
This issue was resolved yesterday.

MAL had a downtime for an hour or two then blocked a huge number of IPs that were from cloud providers/VPNs after it came back up. This included our servers as well.
They unblocked it after 6~ hours. Unsure the exact reason this happened.

Due to this kind of instability - we're reworking how Jikan operates to prevent something like this from disrupting the service again.

**Comment by mysticflute** [comment]
I started noticing this again today, I think it's happening again.

**Comment by irfan-dahir** [comment]
@mysticflute Yep it is. Past 12~ hours.

Pinned issue here: https://github.com/jikan-me/jikan-rest/issues/102#issuecomment-640101348

**Comment by Bluppie05** [comment]
I don't know about you but here it happens again right now...

**Comment by irfan-dahir** [comment]
@Bluppie05 check https://github.com/jikan-me/jikan-rest/issues/123#issuecomment-663598909
