### ISSUE TITLE
Anime in list before 1970 are returned as 20XX

### ISSUE THREAD

**Issue by glugg23** [jikan-me/jikan#291]
I found this while ordering some of the data I'd gotten from my plan to watch list and noticing the oldest entry on it was for some reason displaying as being from 2065.

The response from MAL is this (removed some unnecessary fields):
```
{
    anime_title: "Jungle Taitei",
    anime_id: 1572,
    anime_url: "/anime/1572/Jungle_Taitei",
    anime_start_date_string: "06-10-65",
    anime_end_date_string: "28-09-66",
}
```

This gets parsed by Jikan to:
```
{
    "mal_id": 1572,
    "title": "Jungle Taitei",
    "url": "https://myanimelist.net/anime/1572/Jungle_Taitei",
    "start_date": "2065-10-06T00:00:00+00:00",
    "end_date": "2066-09-28T00:00:00+00:00",
}
```

This is being done by `Parser::parseDateDMY` and the issue lies [here](https://github.com/jikan-me/jikan/blob/4e3781e1617047921d20acc7bb4390bc8e83502d/src/Helper/Parser.php#L135). According to [PHP docs](https://www.php.net/manual/en/datetime.createfromformat.php) the `y` format character assumes the date is between 1970 - 2069 so in this case it assumes the date is for 2065.

Not sure what the best way to fix this would be, as from a quick glance I can find anime on MAL from 1917. So a special case for handling years between 30 and 69 as 1930 to 1969 would still break for some entries.

**Comment by irfan-dahir** [comment]
This is a weird issue. I'm not quite sure how to tackle this appropriately either. MAL makes it worse by returning just the last 2 digits as well. As you said, a special handling for early years won't work either.

I'm leaving this open for discussion to welcome anyone who'd like to pitch a possible fix for this.

**Comment by Teranode** [comment]
How about something like this solution: 
https://stackoverflow.com/a/33581109/3631576
