### ISSUE TITLE
Season: airing_start key missing from newer seasons

### ISSUE THREAD

**Issue by AniLeo** [jikan-me/jikan#298]
https://api.jikan.moe/v3/season/2020/winter
On older seasons, there's an `airing_start` timestamp parameter

https://api.jikan.moe/v3/season/2020/spring
https://api.jikan.moe/v3/season/2020/summer
On spring/summer 2020 seasons, that parameter is gone from every anime

On fall 2020 season, the key exists again, with the respective null and timestamp values for anime that have and don't have airing dates yet
https://api.jikan.moe/v3/season/2020/fall

On winter 2021, the `airing_start` key is also missing
https://api.jikan.moe/v3/season/2021/winter

**Comment by AniLeo** [comment]
The `airing_start` key is now back, seems to have disappeared while MAL was down and reappared once MAL came back and Jikan recached the reply

**Comment by irfan-dahir** [comment]
Thanks for reporting, I have an idea of what could be causing this.

The data was being returned was generated from local cache because Jikan couldn't access MAL. I must've forgotten to include `airing_start` for the generated response. Will fix.

**Comment by irfan-dahir** [comment]
Added.
