### ISSUE TITLE
https://api.jikan.moe/v3/character/1

### ISSUE THREAD

**Issue by s270398** [jikan-me/jikan#299]
{"status":403,"type":"BadResponseException","message":"Jikan failed to connect to MyAnimeList. MyAnimeList may be down\/unavailable or refuses to connect","error":"403 on https:\/\/myanimelist.net\/character\/1"}

**Comment by irfan-dahir** [comment]
MAL was unavailable. Issue similar to https://github.com/jikan-me/jikan-rest/issues/102#issuecomment-640101348

Should be working now. Try it out

**Comment by irfan-dahir** [comment]
Should be fine now. Can't do much if MAL prevents requests in the future though.
Closed.
