### ISSUE TITLE
[OFFICIAL] Generated Issue: ParserException

### ISSUE THREAD

**Issue by spyderbibek** [jikan-me/jikan#300]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```v2.16.5@f471981223b98ef5b69ebced45247687661777ca```
**PHP:** ```7.4.6```
**Redis**: ``````
**Exception:** ```Jikan\Exception\ParserException```
**Code:** ```0```
**Message:** ```Failed to parse 'https://myanimelist.net/history/spyderbibek/anime'```
**Trace:** ```/var/www/jikan/vendor/jikan-me/jikan/src/Exception/ParserException.php on line 24```
**Request:** `GET /v3/user/spyderbibek/history/anime`

**Comment by irfan-dahir** [comment]
Works now ✅
http://api.jikan.moe/v3/user/spyderbibek/history/anime
