### ISSUE TITLE
Music: Opening/Ending Themes

### ISSUE THREAD

**Issue by hwkerr** [jikan-me/jikan#302]
Would like access to an anime's opening and ending themes.

**Comment by irfan-dahir** [comment]
You can access it through the anime endpoint.
e.g https://api.jikan.moe/v3/anime/1

Doc ref: https://jikan.docs.apiary.io/#reference/0/anime

It's `opening_themes` and `ending_themes` respectively.

**Comment by hwkerr** [comment]
Ahh thanks! I was under the impression that it wasn't a feature since I didn't see it in the documentation. I see that there's a lot more information when I actually send a request though, thanks!
