### ISSUE TITLE
failed to open stream: Connection refused in 

### ISSUE THREAD

**Issue by gantarjaelani** [jikan-me/jikan#303]
im already try using curl or file_get_contents, both can't get json result

Error log :
`PHP Warning:  file_get_contents(https://api.jikan.moe/): failed to open stream: Connection refused in`

my code
`$results = file_get_contents('https://api.jikan.moe/v3/anime/1');
$results = json_decode($results, true);`

i don't know why, but working fine at localhost xampp and curl or file_get_contents other site no problem.

**Comment by seanbreckenridge** [comment]
```
<?php
$results = file_get_contents('https://api.jikan.moe/v3/anime/1');
$results = json_decode($results, true);
var_dump($results);
```
seems to work fine for me.

is this on a server somewhere, can you use the `curl`/`wget` command from the command line to see if you have some sort of firewall issue?

`curl https://api.jikan.moe`

**Comment by irfan-dahir** [comment]
`failed to open stream: Connection refused`
Is a server side response. Your IP is probably flagged for abuse by our system and blocked.

If you email me your IP, I can take a look.
neko@jikan.moe

or DM me (Nekomata) if you're on our discord
discord.jikan.moe

**Comment by irfan-dahir** [comment]
Resolved through DM.
