### ISSUE TITLE
[Enhancement] Adding Mutation Testing

### ISSUE THREAD

**Issue by Julien-Broyard** [jikan-me/jikan#304]
Hey I was thinking about adding [Infection](https://infection.github.io/guide/) which is a PHP mutation testing framework based on AST (Abstract Syntax Tree) mutations.

Using it could help preventing bugs by having better tests.

Would this be useful for Jikan ?

**Comment by irfan-dahir** [comment]
Very late to this discussion as tests during v3's development were unironically not a priority for me. 

Infection looks very interesting but feels overkill for Jikan (perhaps it would be useful for something with very complex data). I think it would be simpler to stick to something like #371 .
Thank you for the suggestion.
