### ISSUE TITLE
possible payload

### ISSUE THREAD

**Issue by sinkaroid** [jikan-me/jikan#305]
while i using yer api, i just trying input some basic payload xss,
```
//<iframe src=javascript&colon;alert&lpar;document&period;cookie&rpar;>//
```
then i get that stored cookie
![Screenshot_570](https://user-images.githubusercontent.com/12372481/87886665-2e834680-ca49-11ea-8cb5-46c57440fccb.png)

`tis'll be further?

**Comment by irfan-dahir** [comment]
Hi, I'm not sure I follow.
That's the website (https://github.com/jikan-me/website), not the API? 
Where did you try out the payload?

**Comment by sinkaroid** [comment]
yes mb, cause the API always return as JSON isn't? i think u should remove dat search form (jikan.moe). 
here my stored result:

http://prntscr.com/tkvj5t == document.domain
http://prntscr.com/tkvj9i == inject string

http://prntscr.com/tkvjd6 == i try with form and insert doc cookie
http://prntscr.com/tkvjmr ^
http://prntscr.com/tkvjtg == i embeded my avatar and return too

even i didn;t using burpsuite or tamper data, always return according payload request

**Comment by irfan-dahir** [comment]
Hi, thanks for the details.

I would want to keep the search input there for example reasons. Do you think there is any way to handle this issue?

Usually I handle XSS in the backend, but there's no backend on the website. Just static frontend.

**Comment by sinkaroid** [comment]
i think you need to filter any input form jikan.moe and don't forget to strip any html tags, or just block any strange request like WAF

**Comment by irfan-dahir** [comment]
Thanks, however, I don't think this is a security issue so I will be closing this.
