### ISSUE TITLE
Some anime details not displaying gives 403  error

### ISSUE THREAD

**Issue by SaiBalaji22** [jikan-me/jikan#306]
When i try to search for some anime it is not working. For some anime it is working
![Capture](https://user-images.githubusercontent.com/51410810/88404215-377a6c00-cdeb-11ea-8d31-744297bd751e.JPG)

![Capture](https://user-images.githubusercontent.com/51410810/88404138-187bda00-cdeb-11ea-8407-c2a5787917f6.JPG)

**Comment by irfan-dahir** [comment]
Please refer to https://github.com/jikan-me/jikan-rest/issues/123

Closing due to duplication.
