### ISSUE TITLE
Single result search cases don't work (broke again)

### ISSUE THREAD

**Issue by supreme-chocomint** [jikan-me/jikan#308]
Please fill out the details below.

**Summary:**
MAL seems to redirect to person's page whenever the people search query is close enough to their name.

**Steps to reproduce:**
1. Go to http://api.jikan.moe/v3/search/people?q=Ohashi%20Ayaka or http://api.jikan.moe/v3/search/people?q=Ohashi%20Aya

 ### Additional Details 
 **Jikan Parser Version**: ```v2.16.7@2dc17ee5e619a1c3caa450e909dc538f2454ee30```
**PHP:** ```7.3.13-1+ubuntu18.04.1+deb.sury.org+1```
**Redis**: ```Connected```
**Exception:** ```Jikan\Exception\ParserException```
**Code:** ```0```
**Message:** ```Failed to parse 'https://myanimelist.net/people.php?q=Ohashi+Ayaka'```
**Trace:** ```/var/www/jikan/vendor/jikan-me/jikan/src/Exception/ParserException.php on line 24```
**Request:** `GET /v3/search/people?q=Ohashi%20Ayaka`

**Comment by irfan-dahir** [comment]
Fixed in #313 #312. Wait for the existing server cache to expire to see the changes.

**Comment by Seedmanc** [comment]
How long does this usually take? It's been 10 days. A couple of days ago a request like that gave a blank page with a string of text about a server and its OS instead of JSON. Now it returns a JSON error.

**Comment by irfan-dahir** [comment]
@Seedmanc The latest issue you're referring to is completely different though. MAL has been changing a bunch of things since yesterday so I'm assuming it's packaged with that. 

You can track the new issue here:
https://github.com/jikan-me/jikan-rest/issues/136

Thanks for letting me know, I'll look into that.

**Comment by Seedmanc** [comment]
Now requests that have 100% match give zero results. Are MAL redirects not supported yed?
However, the seiyuu.moe that claims to be using Jikan, have no problem with such queries.

**Comment by irfan-dahir** [comment]
@Seedmanc Hmm this was resolved and jikan does support redirects. Not sure why it broke again, will take a look. Meanwhile re opening the issue

**Comment by adiirfan** [comment]
@irfan-dahir  is it already fixed? cant replicate this error, even my self hosted run fine 

jikan ver 2.16.15

**Comment by iSupercell** [comment]
Would you happen to know if there are any temporary ways to get around this issue? I'm getting the same problem as op.

**Comment by irfan-dahir** [comment]
Sorry folks, I still need some time to get to this issue.


> Would you happen to know if there are any temporary ways to get around this issue? I'm getting the same problem as op.

Try out the official MAL API's search

**Comment by irfan-dahir** [comment]
Closing as I'm not having this issue anymore. Additionally, Jikan REST API doesn't scrape MAL search anymore so I'm not supporting this for further maintenance.
