### ISSUE TITLE
No search results for "Fate/Apocrypha"

### ISSUE THREAD

**Issue by Arnab771** [jikan-me/jikan#310]
I've tried the search api with "Fate Apocrypha", "Fate/Apocrypha" and "Apocrypha" but it doesn't respond with any result.

**Comment by irfan-dahir** [comment]
Fixed.

https://api.jikan.moe/v3/search/anime?q=Fate/Apocrypha
[https://api.jikan.moe/v3/search/anime?q=Fate Apocrypha](https://api.jikan.moe/v3/search/anime?q=Fate%20Apocrypha)
https://api.jikan.moe/v3/search/anime?q=Apocrypha

**Comment by Arnab771** [comment]
Yes, it works now. Thank you.
