### ISSUE TITLE
"nicknames" field is always empty in the v3/character response

### ISSUE THREAD

**Issue by Caier** [jikan-me/jikan#311]
If you make a request to the `v3/character` endpoint, the "nicknames" field is always empty, even though they are visible as "alternative_names" when requesting the `v3/search/character` endpoint.

![image](https://user-images.githubusercontent.com/16463378/89090328-8784a000-d3a2-11ea-9393-bfd0fe7b7e99.png)
![image](https://user-images.githubusercontent.com/16463378/89090376-d6323a00-d3a2-11ea-85aa-618230bf2982.png)

**Comment by irfan-dahir** [comment]
Super late to respond here. But I believe this was resolved some time ago.
https://api.jikan.moe/v3/character/36046
