### ISSUE TITLE
[Search] Person search does not return first result

### ISSUE THREAD

**Issue by Larvitar** [jikan-me/jikan#313]
Person search does not return all results that MAL search returns. Example:
`https://myanimelist.net/people.php?q=Kanemoto` returns 4 persons but Jikan  `http://api.jikan.moe/v3/search/person?q=Kanemoto` only returns 3.

Looking through other search results it seems that only the first result is omitted.

**Comment by irfan-dahir** [comment]
Fixed. Wait a bit for the old cache to expire to see the changes.
