### ISSUE TITLE
[HELP] Is there a way to get random images?

### ISSUE THREAD

**Issue by Readtt** [jikan-me/jikan#314]
Is there a way to do something like:
http://api.jikan.moe/v3/search/anime

and it returns with a random image of a character?

**Comment by irfan-dahir** [comment]
Sorry, there's currently no endpoint in Jikan for something like that.

You could use https://github.com/seanbreckenridge/mal-id-cache to randomly select a character ID and send a request to
https://api.jikan.moe/v3/character/1/pictures

where `1` is the character ID

**Comment by Readtt** [comment]
Ah, I see.
