### ISSUE TITLE
Characters & Staff returning empty

### ISSUE THREAD

**Issue by Neoninfinity** [jikan-me/jikan#315]
An example here is https://api.jikan.moe/v3/anime/11757/characters_staff/

Empty arrays are then returned, this seems to be occurring for all ids, however the data is OCASSIONALLY retrieved and is not consistant.

**Comment by irfan-dahir** [comment]
Duplicate https://github.com/jikan-me/jikan-rest/issues/132

Please track the other issue, thanks!
