### ISSUE TITLE
Themes splited at word wrap

### ISSUE THREAD

**Issue by ginnyTheCat** [jikan-me/jikan#317]
If a theme is wraps to the next line like ED2 at [Neon Genesis Evangelion](https://myanimelist.net/anime/30) it is slit in two.
```
      "\"Fly Me to the Moon (Rei",
      "Version)\" by Megumi Hayashibara (ep 5)",
```
I think it happens here because of the #5 in the text

At https://myanimelist.net/anime/34855 it happens without this

**Comment by irfan-dahir** [comment]
Not sure what you mean. Can you provide an example and the request you made that had this issue?

**Comment by ginnyTheCat** [comment]
Sorry I accidentally pressed enter. I completed it now.

**Comment by ginnyTheCat** [comment]
Other example is https://myanimelist.net/anime/33788 ED11

**Comment by irfan-dahir** [comment]
Thanks for reporting this. I'll look into it.

**Comment by Chortowod** [comment]
In getOpeningThemes() regex filter slightly differ from getEndingThemes():
`'/\s?#\d+:/m'` vs `'/\s?#\d+(:|)/m'`
so deleting alternation OR - | - fixing the issue (or just copying regex from getOpeningThemes()) , but I think this was made not accidently but to prevent other bugs so I don't know how it will affect on other results.
And yes I'm talking about PHP-wrapper (jikan-me\jikan\src\Parser\Anime\AnimeParser.php)
