### ISSUE TITLE
No characters and staff data in response

### ISSUE THREAD

**Issue by mozgow** [jikan-me/jikan#318]
When I request character_staff data with this request: https://api.jikan.moe/v3/anime/12015/characters_staff 
I get an empty list of characters and staff:
```
{
   "request_hash":"request:anime:725ca14a58855302930d7a6e2c692aff6e19a54b",
   "request_cached":true,
   "request_cache_expiry":345032,
   "characters":[
      
   ],
   "staff":[
      
   ]
}
```

The anime does have characters and staff: https://myanimelist.net/anime/12015

**Comment by irfan-dahir** [comment]
Fixed in https://github.com/jikan-me/jikan/pull/319.

Track https://github.com/jikan-me/jikan-rest/issues/132 for REST API fix.
