### ISSUE TITLE
Don't remove formatting from manga synposis

### ISSUE THREAD

**Issue by CountryTk** [jikan-me/jikan#320]
Right now the REST API just returns the synopsis with no newlines or anything. Tested with manga "Akumetsu" (mal_id: 1101).

**Comment by pushrbx** [comment]
the anime part of this is fixed in #496

**Comment by irfan-dahir** [comment]
Fixed with release [v4.0.12](https://github.com/jikan-me/jikan/releases/tag/v4.0.12). 

Note: On the public REST API, please wait 24-48 hours for any existing cache to be replaced.
