### ISSUE TITLE
Dependency conflict with Laravel 8

### ISSUE THREAD

**Issue by aniplaylist** [jikan-me/jikan#323]
Hello!

I'm having a dependency conflict when upgrading my Laravel application from version 7 to 8.

Current Jikan version requires `fabpot/goutte": "^3.2"`, which requires `"guzzlehttp/guzzle": "^6.0"`.
However, as of Laravel 8, `"guzzlehttp/guzzle": "^7.0.1"` is required which causes a dependency conflict with jikan when updating.

A solution would be to use `fabpot/goutte": "^4.0"` which use HttpClient instead of Guzzle. 

Thanks for the awesome work 👍

**Comment by fmohican** [comment]
Hi,
I got same problem with freshly Laravel 8.

```
PS XYZ:\XXX\YXZ\XXA\XAS> composer require jikan-me/jikan
Using version ^2.16 for jikan-me/jikan
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for jikan-me/jikan ^2.16 -> satisfiable by jikan-me/jikan[v2.16.0, v2.16.1, v2.16.10, v2.16.11, v2.16.12, v2.16.13, v2.16.14, v2.16.2, v2.16.3, v2.16.4, v2.16.5, v2.16.6, v2.16.7, v2.16.8, v2.16.9].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.1.1].
    - Can only install one of: guzzlehttp/guzzle[7.1.1, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.1.1].
    - Conclusion: install guzzlehttp/guzzle 6.5.x-dev
    - Installation request for guzzlehttp/guzzle (locked at 7.1.1, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.1.1].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by irfan-dahir** [comment]
Hellos 👋

Laravel 8 is currently not supported.

It requires a major change (breaks BC) so probably won't be adding support for it until after the [next major parser version release](https://github.com/jikan-me/jikan/tree/3.0.0).

Will leave the issue open for tracking.

**Comment by fmohican** [comment]
does new branch is usable? even if it beta/alpha I would like to try.

**Comment by irfan-dahir** [comment]
@fmohican Sure. Though, it's currently in alpha. Some stuff is broken, and other stuff may be heavily changed before stable release.

We're currently running an alpha preview of the next REST API version with it too.

http://docs.api.jikan.moe/
http://api.jikan.moe/v4-alpha

**Comment by fmohican** [comment]
Nice, thank you. I will go with alpha and try out.
I just need basic "anime scrapping" with just basic information like title, season, etc...

Thank you!

**Comment by fmohican** [comment]
> @fmohican Sure. Though, it's currently in alpha. Some stuff is broken, and other stuff may be heavily changed before stable release.
> 
> We're currently running an alpha preview of the next REST API version with it too.
> 
> http://docs.api.jikan.moe/
> http://api.jikan.moe/v4-alpha

Where can i find V4? On the branch its only V3.0.0.x-dev and the error persist....
```
composer require jikan-me/jikan:3.0.0.x-dev
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for jikan-me/jikan 3.0.0.x-dev -> satisfiable by jikan-me/jikan[3.0.0.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.1.1].
    - Can only install one of: guzzlehttp/guzzle[7.1.1, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.1.1].
    - Conclusion: install guzzlehttp/guzzle 6.5.x-dev
    - Installation request for guzzlehttp/guzzle (locked at 7.1.1, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.1.1].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by irfan-dahir** [comment]
@fmohican I think I misphrased. v3 parser won't solve the dependency issue. It supports upto Laravel/Lumen 7.x

**Comment by irfan-dahir** [comment]
I haven't made any support for Laravel/Lumen 8.x as of yet. It'll most likely be added after the next major release (i.e after v3) - is what I mean to say.

**Comment by fmohican** [comment]
Thanks for making crystal-clear. I will look forward and use API till V4 is published.

**Comment by aniplaylist** [comment]
I made dirty forks of Jikan & Goutte where I changed Guzzle 6's namespace which allow having both Guzzle 6 & 7 as a dependency. 
You can use it if you want to prepare your Laravel 8 upgrade, but I don't recommend using it in production as I will not maintain it. 

If you want to use it, update jikan dependency in `composer.json` : 
```
"jikan-me/jikan": "dev-master",
```

and add this repo to the repositories list : 
```
"repositories": [
        {
          "type": "vcs",
          "url": "https://github.com/aniplaylist/jikan.git"
        },
]
```

**Comment by Kaishiyoku** [comment]
Any news here?

**Comment by janvernieuwe** [comment]
Should probably look at using https://github.com/php-http/httplug

**Comment by irfan-dahir** [comment]
This issue is now resolved as of release https://github.com/jikan-me/jikan/releases/tag/v3.0.0-beta.1
Thanks @rjd22 for pr #349! 

I've tested it with Lumen 8 (same as Laravel 8) and it works fine. 
@aniplaylist @fmohican Let me know if you guys have any issues otherwise we can go ahead and close this issue.

> v2 - Supports upto Laravel/Lumen 5.x
> v3 - Supports upto Laravel/Lumen 7.x
> v4? - Laravel/Lumen 8.x support

Additionally, a change of plans for the [v4 REST API](https://github.com/jikan-me/jikan-rest/tree/v4). I'll be soon pushing out a version where we'll migrate from Lumen 7.x -> 8.x.

**Comment by aniplaylist** [comment]
I'm closing the issue, everything works fine with v3

Thanks!
