### ISSUE TITLE
[OFFICIAL] Generated Issue: FatalThrowableError

### ISSUE THREAD

**Issue by irfan-dahir** [jikan-me/jikan#326]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```v2.16.12@ca18a33cee6bb48331aeb27d583883629f3d5e81```
**PHP:** ```7.3.20-1+ubuntu18.04.1+deb.sury.org+1```
**Redis**: ```Connected```
**Exception:** ```Symfony\Component\Debug\Exception\FatalThrowableError```
**Code:** ```0```
**Message:** ```Return value of Jikan\Parser\Search\PersonSearchParser::getResults() must be of the type array, null returned```
**Trace:** ```/var/www/jikan/vendor/jikan-me/jikan/src/Parser/Search/PersonSearchParser.php on line 76```
**Request:** `GET /v3/search/people?q=Ohashi%20Ayaka`

**Comment by Seedmanc** [comment]
Now requests that have 100% match give zero results. Are MAL redirects not supported yed?
