### ISSUE TITLE
Endpoint "/anime/{id}/userupdates" returns empty array for One Piece. this is weird.

### ISSUE THREAD

**Issue by xamantra** [jikan-me/jikan#340]
Tried different anime. But they all worked.

### Working Examples:
- **Cowboy Bebop**: https://api.jikan.moe/v3/anime/1/userupdates  (`finished airing`)
- **Attack on Titan Final Season**: https://api.jikan.moe/v3/anime/40028/userupdates  (`currently airing`)
- **Love Live! Superstar!!**: https://api.jikan.moe/v3/anime/41169/userupdates  (`not yet aired`)

### NOT Working:
- **One Piece**: https://api.jikan.moe/v3/anime/21/userupdates  (`currently airing`)

### Screenshots
![image](https://user-images.githubusercontent.com/37391380/109154399-32c6cd80-77a9-11eb-8e66-19022b00a719.png)
![image](https://user-images.githubusercontent.com/37391380/109154450-42dead00-77a9-11eb-97ca-fec76fd2e82e.png)

This is kinda weird because [one piece user updates page](https://myanimelist.net/anime/21/One_Piece/stats?m=all#members) shows normally.

**Comment by irfan-dahir** [comment]
This seems to have resolved itself. If the issue arises again, please feel free to re-open this.

**Comment by xamantra** [comment]
yeah, it seems fine now.
