### ISSUE TITLE
Wrong date in manga

### ISSUE THREAD

**Issue by Daijobou** [jikan-me/jikan#341]
Example https://api.jikan.moe/v3/manga/73939 for https://myanimelist.net/manga/73939

`"prop":{"from":{"day":26,"month":2,"year":2021},"to":{"day":null,"month":null,"year":null}},"string":", 2012"}`

String ", 2012" becomes 2021-02-26 (today)

**Comment by irfan-dahir** [comment]
@janvernieuwe Do you think for this sort of edge case we should just return the day and month as `1`? So it'd be `2021-1-1`
