### ISSUE TITLE
"Did you mean" system for character search

### ISSUE THREAD

**Issue by lesigit** [jikan-me/jikan#345]
Characters often have a different name in MAL than the name they're actually called (ex: Jotaro Kujo/Joutarou Kuujou), So it becomes a pain when people search the current name(Imagine it's on a bot, if they don't add the name in the api I can give them the "Did you mean" array)

**Comment by irfan-dahir** [comment]
Unfortunately, a system like this is not possible at the moment. MAL doesn't return that information as well so we can't parse it either.
