### ISSUE TITLE
[Search] Add "rated" query parameter to manga search

### ISSUE THREAD

**Issue by Aredruss** [jikan-me/jikan#346]
It would be really helpful to add support for this parameter, due to the fact that even mainstream search requests can provide very NSFW results.

Seemingly safe request:
```
https://api.jikan.moe/v3/search/manga?q=jojo
```

One of the results:
```
        {
            "mal_id": 100549,
            "url": "https://myanimelist.net/manga/100549/Keitai_de_Good_Job",
            "image_url": "https://cdn.myanimelist.net/images/manga/1/182365.jpg?s=5f809bc67603c542b6892273def287b9",
            "title": "Keitai de Good Job!",
            "publishing": false,
            "synopsis": "",
            "type": "Doujinshi",
            "chapters": 0,
            "volumes": 1,
            "score": 0,
            "start_date": "2009-09-27T00:00:00+00:00",
            "end_date": "2009-09-27T00:00:00+00:00",
            "members": 200
        }
```
Implementing additional search for manga would really help to avoid such cases.

**Comment by irfan-dahir** [comment]
Hey, sorry for the belated response. This is unfortunately not possible in v3 since the search results are scrapped from MAL.

However, a filter like this has been added to search for v4 beta. You can add a `sfw` query to filter out any adult content.

https://api.jikan.moe/v4/manga?q=jojo&sfw
Docs: https://docs.api.jikan.moe/#operation/getMangaSearch

**Comment by Aredruss** [comment]
> Hey, sorry for the belated response. This is unfortunately not possible in v3 since the search results are scrapped from MAL.
> 
> However, a filter like this has been added to search for v4 beta. You can add a `sfw` query to filter out any adult content.
> 
> https://api.jikan.moe/v4/manga?q=jojo&sfw
> Docs: https://docs.api.jikan.moe/#operation/getMangaSearch

Thank you for your response! 
I'll look into using v4, seems like the solution you advise will do the trick.

**Comment by irfan-dahir** [comment]
Great, I'll go ahead and close this issue. Feel free to open another if you've any other suggestions.
