### ISSUE TITLE
Comma seperated titles for synonyms incorrect

### ISSUE THREAD

**Issue by ToshY** [jikan-me/jikan#347]
**Case**
Shows that have comma's in there titles will get incorrectly split in synonyms (due to `explode`).

**Example**
MAL ID: 15609

Results in synonyms as following:
```
[
    0 => "Kono Naka ni Hitori"
    1 => "Imouto ga Iru! OVA"
    2 => "Kono Naka ni Hitori"
    3 => "Imouto ga Iru! Episode 13"
    4 => "NakaImo"
    5 => "One of Them is My Younger Sister! OVA"
    6 => "Who is Imouto? OVA"
    7 => "NAKAIMO - My Little Sister Is Among Them! OVA"
]
```

While it should be:

```
[
    0 => "Kono Naka ni Hitori, Imouto ga Iru! OVA"
    1 => "Kono Naka ni Hitori, Imouto ga Iru! Episode 13"
    2 => "NakaImo"
    3 => "One of Them is My Younger Sister! OVA"
    4 => "Who is Imouto? OVA"
    5 => "NAKAIMO - My Little Sister Is Among Them! OVA"
]
```

**Solution**

While I was thinking of a possible solution, I don't really know if there's a decent one for this. I personally would just not explode it al all if there's a comma in the original title.

```
[
    0 => "Kono Naka ni Hitori, Imouto ga Iru! OVA, Kono Naka ni Hitori, Imouto ga Iru! Episode 13, NakaImo, One of Them is My Younger Sister! OVA, Who is Imouto? OVA, NAKAIMO - My Little Sister Is Among Them! OVA"
]
```

In the meantime I'll just implode them back in such cases, but I was wondering if maybe someone else had an idea.

**Comment by irfan-dahir** [comment]
Hey, thanks for highlighting this. It's is a bit of an edge case. MAL usually uses a comma delimiter for the title synonyms. 

Unfortunately, I can't think of a solution and I don't think returning it as a string would be a plausible one.

For reference, this is how it's rendered in the HTML - making it difficult to parse separately.

```html
<span class="dark_text">Synonyms:</span> Kono Naka ni Hitori, Imouto ga Iru! OVA, Kono Naka ni Hitori, Imouto ga Iru! Episode 13, NakaImo, One of Them is My Younger Sister! OVA, Who is Imouto? OVA, NAKAIMO - My Little Sister Is Among Them! OVA
```

**Comment by ToshY** [comment]
Yes I'm aware it's kind of difficult to find a decent solution for these edge cases. And I guess you're right that returning a string isn't the best idea, but that was the only "option" I could think of. 

Now that I'm thinking about it, I'm actually curious if the current MyAnimeList API will return this correctly though (I will take a look at this later).

**Comment by ToshY** [comment]
Seems the API returns the correct synonyms (guess my expected result was wrong as well)

```json
{
    "alternative_titles":{
        "synonyms":[
            "Kono Naka ni Hitori, Imouto ga Iru! OVA",
            "Kono Naka ni Hitori, Imouto ga Iru! Episode 13",
            "NakaImo, One of Them is My Younger Sister! OVA",
            "Who is Imouto? OVA",
            "NAKAIMO - My Little Sister Is Among Them! OVA"
        ],
        "en":"",
        "ja":"この中に1人、妹がいる！兄、妹、恋人"
    }
}
```

Well I'll keep using Jikan anyway and do some manual labour for these edge cases.
