### ISSUE TITLE
Anime GET request randomly cutting off characters in title_english, title_synonyms

### ISSUE THREAD

**Issue by eizany** [jikan-me/jikan#348]
**Steps to reproduce:**

Visit in browser or make a GET request to: "https://api.jikan.moe/v3/anime/30276"
Or any title ending with an 'n' (Attack on Titan, Sword Art: Alicization)

See the reply for title_english and title_synonyms miss 'n'. (May be other letters, only seen 'n' missing so far).

**Results:**

```
title: "One Punch Man"

title_english: "One Punch Ma"

title_japanese: "ワンパンマン"

title_synonyms: Array(3) [ "One Punch-Ma", "One-Punch Ma", "OPM" ]
```

It's been working fine until today/yesterday and seems to be a bug, unless I am missing something. Cheers :)

**Comment by irfan-dahir** [comment]
Thanks. Issue most likely related to yesterday's commit https://github.com/jikan-me/jikan/commit/306d423d49561c8bb68925161745d7a4ad4a5e07

Looking into it

**Comment by eizany** [comment]
Might be related, but the synopsis has been stripped of full stops as well.
You can see the synopsis in the GET request/visiting the page. I've included a before and after as well.

**Before:**

![2021-05-27_19-05](https://user-images.githubusercontent.com/50945740/119798639-d91a9000-beca-11eb-863e-0327ed18702f.png)


**After:**


![unknown](https://user-images.githubusercontent.com/50945740/119798759-f3ed0480-beca-11eb-8d87-e708c406ac85.png)

**Comment by irfan-dahir** [comment]
Resolved with https://github.com/jikan-me/jikan/releases/tag/v2.16.22
