### ISSUE TITLE
Can you add in the episode synopsis to the episode API?

### ISSUE THREAD

**Issue by koji98** [jikan-me/jikan#350]
Currently the episode API leaves out the synopsis. Can you add that in as well?

Example synopis: [https://myanimelist.net/anime/1/Cowboy_Bebop/episode/1](https://myanimelist.net/anime/1/Cowboy_Bebop/episode/1)

**Comment by irfan-dahir** [comment]
Episode synopsis is already added though?

https://myanimelist.net/anime/1/Cowboy_Bebop/episode/1 -> 
https://api.jikan.moe/v4/anime/1/episodes/1

**Comment by koji98** [comment]
Oh, I was using the v3 api. Thanks!
