### ISSUE TITLE
Anime/Manga External Links

### ISSUE THREAD

**Issue by irfan-dahir** [jikan-me/jikan#353]
MAL has made this section public now - which means Jikan can parse it.
![image](https://user-images.githubusercontent.com/9166451/126155013-b085a864-a388-49a2-ab97-8fbe1aa1a206.png)

This was only accessible to logged-in users before.

I'll be adding this feature to parser `^2` and `^3`. 

Although I've stated `^2` is maintainence only, this is a feature it should've had from day 1 and has no BC issues - so I'll be making the only exception for this.

---

Will be first added to `^3` to iron out any bugs then will backport it to `^2`

**Comment by irfan-dahir** [comment]
Worth noting, Anime's only available publicly. Manga external links still do not show up.

**Comment by seanbreckenridge** [comment]
@irfan-dahir 

Seems that Manga External Links are public now as well

**Comment by irfan-dahir** [comment]
@seanbreckenridge That's great. Looks like the parser is picking them up too: https://api.jikan.moe/v3/manga/1
