### ISSUE TITLE
[v3.0.0-beta.1] error with Goutte v4

### ISSUE THREAD

**Issue by aniplaylist** [jikan-me/jikan#355]
Hello, I just tried the v3.0.0 beta release and encountered an error with `getUserAnimeList()` /  `getUserMangaList` from `Jikan\MyAnimeList\MalClient` class.

Here's a code sample: 
```php
$malClient = new Jikan\MyAnimeList\MalClient();
$userAnimeListRequest = new Jikan\Request\User\UserAnimeListRequest('username', 0, 7);
$userAnimeList = $malClient->getUserAnimeList($userAnimeListRequest);
```

Error returned: 

```
Call to undefined method Jikan\Goutte\GoutteWrapper::getClient()
```

It looks like `getClient()` was removed from Goutte in v4.

**Comment by irfan-dahir** [comment]
Hey, good catch.

Pushed out https://github.com/jikan-me/jikan/releases/tag/v3.0.0-beta.2 which should resolve this issue. Let me know

**Comment by aniplaylist** [comment]
It works now, thank you!
