### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by r3sist** [jikan-me/jikan#356]
Hello jikan,
Could you please enable PHP 8 in composer? I have tried to install v3-dev branch. Or dou you think it would generate BC issues or incompatibilities? (I am not familiar with your code base yet. And also, I'm sorry if you discussed this topic somewhere else I did not find.)

https://www.php.net/manual/en/migration80.php

Thank you!

**Comment by janvernieuwe** [comment]
I don't expect too many breaks, havent really tested yet though.

**Comment by irfan-dahir** [comment]
Merged. Available from release
https://github.com/jikan-me/jikan/releases/tag/v3.0.0-beta.5
