### ISSUE TITLE
Jikan server is DOWN! (with details) status page is also even down. This is URGENT!

### ISSUE THREAD

**Issue by xamantra** [jikan-me/jikan#357]
### Error Response
```json
{
    "status": 503,
    "type": "BadResponseException",
    "message": "Jikan failed to connect to MyAnimeList. MyAnimeList may be down/unavailable or refuses to connect",
    "error": null
}
```

**NOTE:** MyAnimeList is accessible on my end. So I think this is definitely a Jikan problem.

### Related Errors
- The root endpoint also does not load: `https://api.jikan.moe/v3` with the same response.
- Status URL `https://status.jikan.moe/` does not load and redirects to `https://www.atlassian.com/software/statuspage`.

### Cases
- Tested with VPN (different countries).
- Tested without VPN.
- Restarted my computer.
- Restarted my router.
- My backend also fails to request Jikan. Hosted in Heroku.

### Screenshots

![image](https://user-images.githubusercontent.com/37391380/128617014-631f47c2-f61b-41a9-acc0-ace70f8a5d99.png)

![image](https://user-images.githubusercontent.com/37391380/128617028-176c42dc-4496-41fe-8d15-4386f6141fd8.png)

![image](https://user-images.githubusercontent.com/37391380/128617099-9860579b-3b7e-4d37-8c00-402ba2e0f3a6.png)

**Comment by xamantra** [comment]
My backend is also now failing. Urgent please...

![image](https://user-images.githubusercontent.com/37391380/128617181-da312ce8-7354-4d82-8ec0-6473ce53e723.png)

My backend doesn't do a DDOS because it only fetches jikan every 24 hours.

Jikan was working perfectly fine before.

**Comment by xamantra** [comment]
pinging you @irfan-dahir

**Comment by seanbreckenridge** [comment]
![image](https://user-images.githubusercontent.com/7804791/128617420-20a7e1fc-2347-4687-a60a-451ce48a2ddf.png)

Theres been an issue with the hosting provider and a DDOS attack on Jikan in addition to that, which is causing the connection issues.

You can [join the discord](http://discord.jikan.moe) for updates

If you urgently need service back, you can [host your own](https://github.com/seanbreckenridge/docker-jikan) dockerized version and point your code at `http://localhost:8000/v3` instead of the remote

**Comment by xamantra** [comment]
Oh, I see. You guys have discord. I'll try joining later.

The backend I'm talking about is being used in an app that isn't published yet so it's kinda fine.

**Comment by xamantra** [comment]
Too lazy to set up my own localhost. I'll just wait :)

**Comment by skelikDev** [comment]
We have the same error. 
We didnt do a lot of requests. But now, to be sure, I have created a delay of 4 seconds

**Comment by irfan-dahir** [comment]
![image](https://user-images.githubusercontent.com/9166451/128631415-3be95ee6-3dff-4691-b6c5-b6da0186289f.png)

Unfortunately, the ddos attack is still ongoing but it's no longer an issue as we've a system in place now that is automatically monitoring requests and flagging suspicious IPs.

If you think your IP has been mistakenly flagged (e.g the attacker's IP gets recycled to you), you can use https://api.jikan.moe/am-i-banned/ to check if it's blocked and then let us know - we'll remove it promptly.
