### ISSUE TITLE
Wrong gender.

### ISSUE THREAD

**Issue by H-M-H** [jikan-me/jikan#358]
```sh
$ curl -s https://api.jikan.moe/v3/user/evyich | jq .gender
" Location: Stalk me more "
```
I suspect this filter: https://github.com/jikan-me/jikan/blob/4bbcd97c70e4b14e0713456d28d83ee6e42a30ab/src/Parser/User/Profile/UserProfileParser.php#L128 is insufficient.

**Comment by irfan-dahir** [comment]
The issue has been resolved. Please wait for the existing cache to expire before you can see the changes.
