### ISSUE TITLE
[Fix] Character's pictures Request returns the pictures twice

### ISSUE THREAD

**Issue by WildCyclotron** [jikan-me/jikan#359]
Let's say I want to search for the pictures of a character with id say `180844`

```py
from urllib.request import Request, urlopen

request = Request('https://api.jikan.moe/v3/character/180844/pictures')

response_body = urlopen(request).read()
print(response_body)
```
On mal this character has two images so it should return two `large` and two `short` images but the output is something like: 
```
{'pictures': [{'large': 'https://cdn.myanimelist.net/images/characters/3/405871.jpg', 'small':
'https://cdn.myanimelist.net/images/characters/3/405871.jpg'}, {'large':
'https://cdn.myanimelist.net/images/characters/6/417850.jpg', 'small':
'https://cdn.myanimelist.net/images/characters/6/417850.jpg'}, {'large':
'https://cdn.myanimelist.net/images/characters/3/405871.jpg', 'small':
'https://cdn.myanimelist.net/images/characters/3/405871.jpg'}, {'large':
'https://cdn.myanimelist.net/images/characters/6/417850.jpg', 'small':
'https://cdn.myanimelist.net/images/characters/6/417850.jpg'}]}
```
It sends four `large` images and four `small` images in which the latter are same as the starting ones.

**Comment by irfan-dahir** [comment]
### The problem
is that MAL does not have any large image sizes for Character pictures. And the Anime/Manga/Character/People pictures are obtained by a common parser class.

Whereas the default for this particular image would be:
https://cdn.myanimelist.net/images/characters/3/405871.jpg

The large size would be this respectively;
https://cdn.myanimelist.net/images/characters/3/405871l.jpg 

---

### Before vs now

However, this now returns a 404. Before, it did not return a 404 and just served the same image size as the default one for `large` too.

---

### the fix
Is to completely remove the `large` picture URL so it only serves the default size for character pictures specifically.

**Comment by seanbreckenridge** [comment]
Hmm - not sure if this is related to this issue, but seems that all characters now return empty array for pictures:

https://api.jikan.moe/v3/character/1/pictures

**Comment by irfan-dahir** [comment]
Pushed the patch for v3 REST. Please wait for any cache to invalidate for the changes to show up.

![image](https://user-images.githubusercontent.com/9166451/135637050-595c07f6-194d-4b74-82eb-c2f8d6327010.png)
