### ISSUE TITLE
[Bug] Recent manga review has wrong entry parser

### ISSUE THREAD

**Issue by javoeria** [jikan-me/jikan#360]
Hi, the endpoint https://api.jikan.moe/v4/reviews/manga always returns null to the "entry" key.
I think it can be fixed by changing this line with "$instance->entry" like in the RecentAnimeReview file.

https://github.com/jikan-me/jikan/blob/bfb0d71099483e5b8ece81a2607e92b3a0614861/src/Model/Reviews/Recent/RecentMangaReview.php#L42

Thanks.

**Comment by javoeria** [comment]
Any updates?

**Comment by irfan-dahir** [comment]
Thank you for reporting this. Sorry for the delay. Please wait for any cache to expire.
