### ISSUE TITLE
[OFFICIAL] Generated Issue: ParserException

### ISSUE THREAD

**Issue by mozgow** [jikan-me/jikan#361]
Please fill out the details below.

**Summary:**
Requesting characters data for anime returns error with exception.

**Steps to reproduce:**
Just send a request to: https://api.jikan.moe/v3/anime/2605/characters_staff

 ### Additional Details 
 **Jikan Parser Version**: ```v2.16.22@b9fce92e535e28ab462f495fea167d7e80836634```
**PHP:** ```7.3.28-2+ubuntu18.04.1+deb.sury.org+1```
**Redis**: ```Connected```
**Exception:** ```Jikan\Exception\ParserException```
**Code:** ```0```
**Message:** ```Failed to parse 'https://myanimelist.net/anime/2605/_/characters'```
**Trace:** ```/var/www/jikan/vendor/jikan-me/jikan/src/Exception/ParserException.php on line 24```
**Request:** `GET /v3/anime/2605/characters_staff`

**Comment by mozgow** [comment]
The same error is also reported for https://api.jikan.moe/v3/anime/16/characters_staff and https://api.jikan.moe/v3/anime/21995/characters_staff

**Comment by irfan-dahir** [comment]
The issue has been resolved. Please wait for the existing cache to expire before you can see the changes.
