### ISSUE TITLE
Demographics is not returned for the anime

### ISSUE THREAD

**Issue by mozgow** [jikan-me/jikan#363]
Demographics is not returned for the anime.

I've checked:
https://api.jikan.moe/v3/anime/34019
https://api.jikan.moe/v3/anime/15
https://api.jikan.moe/v3/anime/16
https://api.jikan.moe/v3/anime/28735

and the response for all of them is:
```
"demographics":[
      
   ],
```

It does seem to work for manga, but the name is a bit messy:
```
"demographics":[
      {
         "mal_id":42,
         "type":"manga",
         "name":"\n                Josei",
         "url":"https:\/\/myanimelist.net\/manga\/genre\/42\/Josei"
      }
   ],
```

**Comment by irfan-dahir** [comment]
Thanks, have pushed a working patch for both of the issues. Changes will take effect as soon as the cache expires.

**Comment by irfan-dahir** [comment]
Any incorrect cache should've been invalidated by now. Feel free to re-open the issue if you come across it again.

Thanks!
