### ISSUE TITLE
Opening/Ending Themes - New Info

### ISSUE THREAD

**Issue by seanbreckenridge** [jikan-me/jikan#365]
MAL has updated the OP/ED section for OP/EDs, assumedly connecting it to a scrobbling service to add streaming links:

![](https://media.discordapp.net/attachments/461199124205797439/892512885962604614/unknown.png?width=364&height=277)

![](https://media.discordapp.net/attachments/461199124205797439/892510403932872734/unknown.png?width=358&height=166)

New Section on the Videos Page as well:

https://myanimelist.net/anime/5114/Fullmetal_Alchemist__Brotherhood/video

Hence, the opening/ending themes for all entries are not returned anymore, page has been restructured a bit

---

Additional Possible Feature; just to mention it

Not sure if the actual streaming aspect is something that we'd want to add to Jikan, but I think it is possible? Otherwise, just thought I'd mention it somewhere so its documented:

```javascript
        function playPreview(oped_id, spotify_id) {
          const previewApiUrl = '/spotify/get_preview_url/' + spotify_id;
          const preview = document.querySelector("#preview_" + oped_id);
          $.ajax({
            url: previewApiUrl,
            type: "GET",
            timeout: 10000,
            success: function(data) {
              if (data.preview_url) {
                preview.src = data.preview_url;
                controlPreview(oped_id);
              }
            }
          });
        }
```

The JS on the page pulls an ID from the page, so we could return this url/ID (not make the request on Jikan's end, just return the ID)

```
$ curl 'https://myanimelist.net/spotify/get_preview_url/4OQq1bcP12GQQXJNupxqfR' | jq -r '.preview_url'
https://p.scdn.co/mp3-preview/355971c26602bfd90814f94fa6f2e0cc7c29a813?cid=9027c8a46e7e4be5b25b70053dfd0708
```

which could then be used to get a 30s preview of OP/EDs, the vanish/proxy CDN in front of it doesn't seem to require auth

**Comment by irfan-dahir** [comment]
Thanks, @seanbreckenridge!

I'll put out a patch in a bit to have the v2 parser return data like before to prevent breaking changes. 

The additional data would be best returned in the v3 parser (REST v4)

**Comment by irfan-dahir** [comment]
Re-opened for v3 parser. We can implement a new structure for it there.

**Comment by irfan-dahir** [comment]
Pushed the patch for v3 REST. Looks good now, please wait for any cache to invalidate for the changes to show up.
![image](https://user-images.githubusercontent.com/9166451/135636829-c0b91fea-ec13-4eba-b1a3-3dddac6ab0a8.png)
