### ISSUE TITLE
Remove php-vcr tests in favour of real integration tests

### ISSUE THREAD

**Issue by rjd22** [jikan-me/jikan#371]
At this moment the test suite 3.0.0 is broken. The tests that are written are based on php-vcr but don't really tell us if our intergration with MAL is really working. Thus it's not telling us if the library is working.

I would recommend moving to integration tests that actually test by sending real request to MAL. This might sound counter intuitive and yes tests will break if MAL changes but I feel that testing if the integration with MAL is working is the whole goal of the tests.

@irfan-dahir what do you think?

**Comment by janvernieuwe** [comment]
Hello 429 my old friend

**Comment by rjd22** [comment]
@janvernieuwe It would also be okay if we would have some automated way to update the fixtures on a regular (once a day/week?) basis and run the tests against those.

**Comment by janvernieuwe** [comment]
If you comment \VCR\VCR::turnOn();, or create a bootstrap without it, it will request to MAL.
Still... you'll be rate limited so fast....

**Comment by irfan-dahir** [comment]
A bit late to this discussion, but we might be able to run an external scheduler to update the fixtures with some delay. 

But I'm not sure what the best approach for this would be. Any suggestions?

**Comment by irfan-dahir** [comment]
Tests fixed as of #418
