### ISSUE TITLE
Friends returns empty

### ISSUE THREAD

**Issue by riccardocescon** [jikan-me/jikan#378]
When i ask for the friend list i always get empty.
`
Url : https://api.jikan.moe/v3/user/{username}/friends/1
`
Response Body : 
`
{"request_hash":"request:user:{hash}","request_cached":true,"request_cache_expiry":820,"friends":[]}
`

**Comment by irfan-dahir** [comment]
Thanks for reporting. A fix has been pushed. Please wait up to an hour for any empty friend list cache to expire.
