### ISSUE TITLE
[OFFICIAL] Person Parsing Error

### ISSUE THREAD

**Issue by romebell** [jikan-me/jikan#380]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```v2.18.9@c80d751b3878a0c7de42d78854b5c590230a0622```
**PHP:** ```7.4.23```
**Redis**: ```Connected```
**Exception:** ```Jikan\Exception\ParserException```
**Code:** ```0```
**Message:** ```Failed to parse 'https://myanimelist.net/people/1'```
**Trace:** ```/var/www/jikan/vendor/jikan-me/jikan/src/Exception/ParserException.php on line 24```
**Request:** `GET /v3/person/1`

**Comment by irfan-dahir** [comment]
Thanks for reporting. A fix has been pushed.
