### ISSUE TITLE
500 (Internal Server Error) with using search endpoint (Anohana)

### ISSUE THREAD

**Issue by matthewhirai** [jikan-me/jikan#381]
Summary:
When using the search endpoint for 'Anohana' it gives a 500 internal server error.  I checked the search API on jikan.moe and it works. It seems like Anohana is the only one giving that error; everything else works fine
Update:
It seems like anime with 'A' at the beginning seem to get the same error (Angel Beats [also doesn't work in jikan.moe], Adachi to Shimamura)

Steps to reproduce:
anime = 'anohana'
![image](https://user-images.githubusercontent.com/61099117/147325303-6dfbae9d-bd3b-4c9e-91fd-a98f52b1831c.png)

Result:
`{"status":500,"type":"ParserException","message":"Unable to parse this request. Please follow report_url to generate an issue on GitHub","error":"Failed to parse 'https:\/\/myanimelist.net\/anime.php?q=anohana&type=0&score=0&status=0&p=0&r=0&sd=0&sm=0&sy=0&ed=0&em=0&ey=0&gx=0&c[]=a&c[]=b&c[]=c&c[]=f&c[]=d&c[]=e&c[]=g'","report_url":"https:\/\/github.com\/jikan-me\/jikan\/issues\/new?title=%5BOFFICIAL%5D+Generated+Issue%3A+ParserException&body=Please+fill+out+the+details+below.%0A%0A%2A%2ASummary%3A%2A%2A%0A%0A%2A%2ASteps+to+reproduce%3A%2A%2A%0A%0A%0A%0A+%23%23%23+Additional+Details+%0A+%2A%2AJikan+Parser+Version%2A%2A%3A+%60%60%60v2.18.9%40c80d751b3878a0c7de42d78854b5c590230a0622%60%60%60%0A%2A%2APHP%3A%2A%2A+%60%60%607.4.23%60%60%60%0A%2A%2ARedis%2A%2A%3A+%60%60%60Connected%60%60%60%0A%2A%2AException%3A%2A%2A+%60%60%60Jikan%5CException%5CParserException%60%60%60%0A%2A%2ACode%3A%2A%2A+%60%60%600%60%60%60%0A%2A%2AMessage%3A%2A%2A+%60%60%60Failed+to+parse+%27https%3A%2F%2Fmyanimelist.net%2Fanime.php%3Fq%3Danohana%26type%3D0%26score%3D0%26status%3D0%26p%3D0%26r%3D0%26sd%3D0%26sm%3D0%26sy%3D0%26ed%3D0%26em%3D0%26ey%3D0%26gx%3D0%26c%5B%5D%3Da%26c%5B%5D%3Db%26c%5B%5D%3Dc%26c%5B%5D%3Df%26c%5B%5D%3Dd%26c%5B%5D%3De%26c%5B%5D%3Dg%27%60%60%60%0A%2A%2ATrace%3A%2A%2A+%60%60%60%2Fvar%2Fwww%2Fjikan%2Fvendor%2Fjikan-me%2Fjikan%2Fsrc%2FException%2FParserException.php+on+line+24%60%60%60%0A%2A%2ARequest%3A%2A%2A+%60GET+%2Fv3%2Fsearch%2Fanime%3Fq%3Danohana%26limit%3D20%60%0A"}`

**Comment by irfan-dahir** [comment]
Thanks for reporting. A fix has been pushed.
