### ISSUE TITLE
[OFFICIAL] Generated Issue: ParserException

### ISSUE THREAD

**Issue by BooleanCube** [jikan-me/jikan#382]
The API keeps returning a ParserException when I try to connect to the REST API instead of giving me the data.

**Summary:**
The API doesn't allow me to search for animes in my application. However, searching for characters works.

**Steps to reproduce:**
Using a search request with anime parameter doesn't work for any search query.

 ### Additional Details 
 **Jikan Parser Version**: ```v2.18.9@c80d751b3878a0c7de42d78854b5c590230a0622```
**PHP:** ```7.4.23```
**Redis**: ```Connected```
**Exception:** ```Jikan\Exception\ParserException```
**Code:** ```0```
**Message:** ```Failed to parse 'https://myanimelist.net/anime.php?q=mob&type=0&score=0&status=0&p=0&r=0&sd=0&sm=0&sy=0&ed=0&em=0&ey=0&gx=0&c[]=a&c[]=b&c[]=c&c[]=f&c[]=d&c[]=e&c[]=g'```
**Trace:** ```/var/www/jikan/vendor/jikan-me/jikan/src/Exception/ParserException.php on line 24```
**Request:** `GET /v3/search/anime?q=mob`

**Comment by irfan-dahir** [comment]
Closing: Duplicate #381. Please track it there.
