### ISSUE TITLE
[OFFICIAL] Generated Issue: ParserException

### ISSUE THREAD

**Issue by Ervie** [jikan-me/jikan#384]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```v2.18.11@5cf72e1616ae7adefc51447ca62f9331ca76a51a```
**PHP:** ```7.4.23```
**Redis**: ```Connected```
**Exception:** ```Jikan\Exception\ParserException```
**Code:** ```0```
**Message:** ```Failed to parse 'https://myanimelist.net/people/1870'```
**Trace:** ```/var/www/jikan/vendor/jikan-me/jikan/src/Exception/ParserException.php on line 24```
**Request:** `GET /v3/person/1870`

Dunno if this is related to https://github.com/jikan-me/jikan/issues/380 or maybe some cache? I see it's working just fine on some other ids

**Comment by irfan-dahir** [comment]
Fixed: https://api.jikan.moe/v3/person/1870

Thanks for reporting!

**Comment by Ervie** [comment]
Stellar job!
