### ISSUE TITLE
[OFFICIAL] Generated Issue: ParserException

### ISSUE THREAD

**Issue by NateShoffner** [jikan-me/jikan#385]
Please fill out the details below.

**Summary:**

Appears to be a parser issue with Genre by ID endpoint.

**Steps to reproduce:**

Request any genre by ID.

 ### Additional Details 
 **Jikan Parser Version**: ```v2.18.13@d41c4535bb739824c61ae22192c41eb3b705399c```
**PHP:** ```7.4.23```
**Redis**: ```Connected```
**Exception:** ```Jikan\Exception\ParserException```
**Code:** ```0```
**Message:** ```Failed to parse 'https://myanimelist.net/anime/genre/12?page=1'```
**Trace:** ```/var/www/jikan/vendor/jikan-me/jikan/src/Exception/ParserException.php on line 24```
**Request:** `GET /v3/genre/anime/12/1`

**Comment by irfan-dahir** [comment]
Fixed, but there may be some information missing. Please read:
https://github.com/jikan-me/jikan/issues/386#issuecomment-1007730535
