### ISSUE TITLE
[HOSTED] Generated Issue: ParserException

### ISSUE THREAD

**Issue by i-none** [jikan-me/jikan#387]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```3.0.0.x-dev@d82323e4588b755c0090cd71d0420d514218668a```
**PHP:** ```8.0.2```
**Redis**: ``````
**Exception:** ```Jikan\Exception\ParserException```
**Code:** ```0```
**Message:** ```Failed to parse 'https://myanimelist.net/anime/season/2021/winter'```
**Trace:** ```D:\Projects\MAL\vendor\jikan-me\jikan\src\Exception\ParserException.php on line 24```
**Request:** `GET /v4/seasons/2021/winter`

**Comment by irfan-dahir** [comment]
Fixed, thanks for reporting. Update your jikan parser
`composer update jikan-me/jikan`
