### ISSUE TITLE
Industry News

### ISSUE THREAD

**Issue by LuckyYam** [jikan-me/jikan#391]
In the v4, the api can only return the news for a given anime/manga id. So, I would like to request to add a endpoint for returning news info when valid news id is provided.

**Comment by LuckyYam** [comment]
.

**Comment by irfan-dahir** [comment]
# Definition/Requirement

## Endpoints

### News Tags

News Tags: https://myanimelist.net/news/tag

```php
$jikan->getNewsTags($request)
```

### Recent News

Recent News: https://myanimelist.net/news?p=1

```php
$jikan->getNews(new NewsRequest(int $page))
```

### News By Tag

News By Tag: https://myanimelist.net/news/tag/new_anime

```php
$jikan->getNewsByTag(new NewsByTagRequest(string $tag, int $page))
```

### News Search

News Search: https://myanimelist.net/news/search?q=bleach

```php
$jikan->getNewsSearch(new NewsSearchRequest(string $query, int $page))
```


## Response Objects

### News/Tags

Categories
- Anime
- Manga
- People
- Music
- Events
- Industry


### News/Tag

Tags[] in each Category
| Property  |  Type | Remarks |
| ------------- | ------------- | ------------- |
| `mal_id` | String | Tag name (canonical) |
| `name` | String | Tag name |
| `url` | String | News listing by tag URL |
| `description` | String | - |


### NewsByID

MAL URL: https://myanimelist.net/news/66771438
| Property  |  Type | Remarks |
| ------------- | ------------- | ------------- |
| `mal_id` | String | News ID |
| `url` | String | - |
| `forum_url` | String | URL to comments - so it can be parsed by MAL's API | 
| `title` | String | News title|
| `date` | String | ISO8601 |
| `content` | String | Unparsed HTML response (like user about mes'?) |
| `user` | `UserMeta` | Author user object |
| `comments` | Integer | Comment count |
| `relations` | Objects of `MalUrl[]` | Same as relation is done in `getAnime` & `getManga` | 
| `tags` | TagMeta[] | Array of tag metadata objects (mal_id, name, URL) |


### Results

The following will implement [Results](https://github.com/jikan-me/jikan/blob/master/src/Model/Common/Collection/Results.php).

- Recent News
- News By Tag
- News Search

`getResults()` will return an array of `NewsListItem`

### NewsListItem

| Property  |  Type | Remarks |
| ------------- | ------------- | ------------- |
| `mal_id` | String | News ID |
| `url` | String | - |
| `images` | Images Object | Need to look into available formats & sizes |
| `forum_url` | String | URL to comments - so it can be parsed by MAL's API | 
| `title` | String | News title|
| `date` | String | ISO8601 |
| `excerpt` | String | - |
| `user` | `UserMeta` | Author user object |
| `comments` | Integer | Comment count | 
| `tags` | TagMeta[] | Array of tag metadata objects (mal_id, name, URL) |

**Comment by irfan-dahir** [comment]
Superseded by https://github.com/jikan-me/jikan-rest/issues/535
