### ISSUE TITLE
[OFFICIAL] Generated Issue: ParserException

### ISSUE THREAD

**Issue by Ervie** [jikan-me/jikan#394]
Please fill out the details below.

**Summary:** Pretty much the same as for anime moreinfo endpoint.

**Steps to reproduce:** Go to any manga more info endpoint" https://docs.api.jikan.moe/#operation/getMangaMoreInfo

 ### Additional Details 
 **Jikan Parser Version**: ```3.0.0.x-dev@df9adebbf2cab15b603a0afb5392b9501416e6e7```
**PHP:** ```8.0.14```
**Redis**: ```Connected```
**Exception:** ```Jikan\Exception\ParserException```
**Code:** ```0```
**Message:** ```Failed to parse 'https://myanimelist.net/manga/1/_/moreinfo'```
**Trace:** ```/var/www/jikan-rest/vendor/jikan-me/jikan/src/Exception/ParserException.php on line 24```
**Request:** `GET /v4/manga/1/moreinfo`

**Comment by irfan-dahir** [comment]
Fixed, thanks!
