### ISSUE TITLE
[OFFICIAL] Generated Issue: ParserException

### ISSUE THREAD

**Issue by giito0101** [jikan-me/jikan#396]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```v2.19.3@e3a673b37d23fbf4152ab0c2c2ac483ea8fd016d```
**PHP:** ```7.4.23```
**Redis**: ```Connected```
**Exception:** ```Jikan\Exception\ParserException```
**Code:** ```0```
**Message:** ```Failed to parse 'https://myanimelist.net/anime/producer/1?page=1'```
**Trace:** ```/var/www/jikan/vendor/jikan-me/jikan/src/Exception/ParserException.php on line 24```
**Request:** `GET /v3/producer/1/1?`

**Comment by irfan-dahir** [comment]
This is now fixed. However, However, MAL changed the data available on the page. So the following are not available any more and will return `null`:
`producers`, `synopsis`, `themes`, `type`, `genres`, `demographics`, `source`, `licensors`

Please upgrade to REST API v4 to resolve this issue.
V4 Equivalent: https://api.jikan.moe/v4/anime?producers=1
Docs: https://docs.api.jikan.moe/#operation/getAnimeSearch
