### ISSUE TITLE
Include more languages for show alternative titles

### ISSUE THREAD

**Issue by ToshY** [jikan-me/jikan#397]
**Enhancement:**

Alternative titles nowadays have more options than just `English`, `Japanese` and `Synonyms`.
New languages that are available: `German`, `Spanish`, `French`.

[Example](https://myanimelist.net/anime/38000)

**How to fix**

* Add methods similar to `getTitleEnglish` in the `AnimeParser`, just change method name and change the xpath with the new languages.
* Add nullable properties for the new languages in the model `Anime`.

**Version**

`v3.0.0-beta.9`

**Comment by nerg4l** [comment]
Instead of adding more properties to `Anime` do you think it would make sense to expose titles in different languages as `getAlternativeTitles()` and return them as key-value pairs (`['english' => ..., 'german' => ...]`)?

**Comment by pushrbx** [comment]
@nerg4l @irfan-dahir  should this also be part of the search index (laravel scout work)? E.g. do we want to allow users to look for the alternative titles?

**Comment by irfan-dahir** [comment]
I'd agree with the direction @ToshY is thinking in. I've mostly handled additional data as their own model wherever applicable.
