### ISSUE TITLE
[OFFICIAL] Generated Issue: ParserException

### ISSUE THREAD

**Issue by slashbeast** [jikan-me/jikan#398]
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

Fetch https://api.jikan.moe/v4/anime/32268/relations

 ### Additional Details 
 **Jikan Parser Version**: ```3.0.0.x-dev@b619665b0dc73908b794d5c464055a4c786c7b34```
**PHP:** ```8.0.15```
**Redis**: ```Connected```
**Exception:** ```Jikan\Exception\ParserException```
**Code:** ```0```
**Message:** ```Failed to parse 'https://myanimelist.net/anime/32268/'```
**Trace:** ```/var/www/jikan-rest/vendor/jikan-me/jikan/src/Exception/ParserException.php on line 24```
**Request:** `GET /v4/anime/32268`

**Comment by irfan-dahir** [comment]
Seems to be resolved. Feel free to re-open the issue if it occurs again.
