### ISSUE TITLE
get image with anime search

### ISSUE THREAD

**Issue by YeeJiaWei** [jikan-me/jikan#401]
version 3 have anime cover image url in the anime search response, but in v4 I can't find it, anyway to solve it?

It seem currently only can get image though another api

**Comment by irfan-dahir** [comment]
It's in the response - the `images` object.

https://api.jikan.moe/v4/anime?q=bleach
Docs/Schema: https://docs.api.jikan.moe/#operation/getAnimeSearch

**Comment by YeeJiaWei** [comment]
okay, now I found it, thank you
