### ISSUE TITLE
Missing info for "related" in v4

### ISSUE THREAD

**Issue by Daijobou** [jikan-me/jikan#403]
Example https://api.jikan.moe/v3/manga/24567 vs https://api.jikan.moe/v4/manga/24567

in v3
> "related":{"Adaptation":[{"mal_id":2415,"type":"anime","name":"Super Fishing Grander Musashi","url":"https:\/\/myanimelist.net\/anime\/2415\/Super_Fishing_Grander_Musashi"}]},

this part is in v4 missing.

**Comment by irfan-dahir** [comment]
https://api.jikan.moe/v4/manga/24567/relations
Docs: https://docs.api.jikan.moe/#tag/manga

It's separated
