### ISSUE TITLE
v4/seasons: Bug causes only some entries to be listed

### ISSUE THREAD

**Issue by AniLeo** [jikan-me/jikan#404]
I've tested all seasons on 2021 and 2022 and this bug happens on all of them

Let's take **Winter 2022** for example:
- https://myanimelist.net/anime/season/2022/winter
- https://api.jikan.moe/v4/seasons/2022/winter?page=1
- https://api.jikan.moe/v4/seasons/2022/winter?page=2

The API is missing most entries, it's only listing type "TV" entries

Examples of Winter 2022 entries not listed, one per category
- Movie: https://myanimelist.net/anime/49310/Fruits_Basket__Prelude
- OVA: https://myanimelist.net/anime/49521/Non_Non_Biyori_Nonstop_OVA
- ONA: https://myanimelist.net/anime/43693/Thermae_Romae_Novae
- Special: https://myanimelist.net/anime/50360/Mushoku_Tensei__Isekai_Ittara_Honki_Dasu_Special

**Comment by irfan-dahir** [comment]
https://github.com/jikan-me/jikan-rest/issues/217#issuecomment-1111545034
