### ISSUE TITLE
[OFFICIAL] Generated Issue: ParserException

### ISSUE THREAD

**Issue by ScrabbleScratch** [jikan-me/jikan#406]
Please fill out the details below.

**Summary:**
When doing a request to get anime data is pretty common that the request fails and sometimes succeeds by making the exact same request.

**Steps to reproduce:**
Send request: https://api.jikan.moe/v4/anime/51409

 ### Additional Details 
 **Jikan Parser Version**: ```3.0.0.x-dev@a4cf4837ad2c87703db4d7ecb9732cfa59f5c698```
**PHP:** ```8.0.15```
**Redis**: ```Connected```
**Exception:** ```Jikan\Exception\ParserException```
**Code:** ```0```
**Message:** ```Failed to parse 'https://myanimelist.net/anime/51409/'```
**Trace:** ```/var/www/jikan-rest/vendor/jikan-me/jikan/src/Exception/ParserException.php on line 24```
**Request:** `GET /v4/anime/51409`

**Comment by irfan-dahir** [comment]
This is interesting. The anime doesn't exist: https://myanimelist.net/anime/51409
I'm not sure why the 404 isn't getting thrown as an exception for this ID specifically 🤔
