### ISSUE TITLE
Class "Jikan\Model\Common\YoutubeMeta" not found

### ISSUE THREAD

**Issue by nerg4l** [jikan-me/jikan#411]
It seems on Mar 23, 2022 `Jikan\Model\Common\YoutubeMeta` was removed. While looking at the history for [`jikan/src/Model/Common`](https://github.com/jikan-me/jikan/commits/master/src/Model/Common) I could not found the exact commit but while viewing the code at `1b87efc` the class is still there and right after at `b1d5326` the class is gone.

**Comment by pushrbx** [comment]
I'll try to look into this as this problem is preventing me from working on https://github.com/jikan-me/jikan-rest/pull/227.

**Comment by pushrbx** [comment]
There was a revert at af4738c871ced5591ea74f8f27e499de31e2bcc3 which might have confused the merge at 1e72498a6b8bfa6fc9f83f6da1e6ace5d1ccc702

**Comment by irfan-dahir** [comment]
Good catch! Bit of a learning lesson for me. Should rebase after massive changes next time 😅

**Comment by irfan-dahir** [comment]
Fixed with #412
