### ISSUE TITLE
Issue: ParserException

### ISSUE THREAD

**Issue by DeNewGuy1997** [jikan-me/jikan#413]
Hello, I'm trying to use anime search function, but when I'm calling for it I'm getting the following error in Laravel 8.
`Failed to parse 'https://myanimelist.net/anime.php?q=No+Game+No+Life&type=0&score=0&status=0&p=0&r=0&sd=0&sm=0&sy=0&ed=0&em=0&ey=0&gx=0&c[]=a&c[]=b&c[]=c&c[]=f&c[]=d&c[]=e&c[]=g'`

My Code:
```
$animeSearchResults = $jikan->getAnimeSearch(
    (new \Jikan\Request\Search\AnimeSearchRequest("No Game No Life"))
);
dd($animeSearchResults);
```

I don't know if this is on me or not, but would appreciate any help. :)
Thanks in advance.

### Additional Details:

**Jikan Version:** `3.0.1`
**PHP:** `8.1.6`
**Laravel Version:** `8.83.15`
**Exception:** `Jikan\Exception\ParserException`

**Comment by pushrbx** [comment]
Will be fixed in next release.

**Comment by DeNewGuy1997** [comment]
> Will be fixed in next release.

Thank you!
