### ISSUE TITLE
Anime Episodes

### ISSUE THREAD

**Issue by irfan-dahir** [jikan-me/jikan#446]
- Add poll average
- Fix episodes not parsing for entries (tested with IDs [1](https://api.jikan.moe/v4/anime/1/episodes?page=1), [5](https://api.jikan.moe/v4/anime/5/episodes?page=1), [21](https://api.jikan.moe/v4/anime/21/episodes?page=1))

**Comment by Cryental** [comment]
Bug is also occurred for some entries, which is null exception for getVideoUrl and forum url.

**Comment by Cryental** [comment]
Also parsing error for 1337, 6171, 29603, 1881, 910 and 352.

**Comment by Cryental** [comment]
Happening with latest 3.1.0 version.

**Comment by AbhiramH427** [comment]
Empty Data for every [Anime](https://api.jikan.moe/v4/anime/20583/episodes)

![image](https://user-images.githubusercontent.com/69304096/176935936-f2daa12d-9b11-45c6-8248-5e8809bc7bbf.png)
