### ISSUE TITLE
Some manga stats fail to parse

### ISSUE THREAD

**Issue by irfan-dahir** [jikan-me/jikan#449]
Requests:
https://api.jikan.moe/v4/manga/134064/statistics
https://api.jikan.moe/v4/manga/5611/statistics

Sentry: https://sentry.io/share/issue/0397aa9ef5c9492b85e485c888e87cac/

**Comment by pushrbx** [comment]
That sentry thing is awesome, would it be possible to include that link in the generated issues?

**Comment by irfan-dahir** [comment]
@pushrbx I'll look into it
