### ISSUE TITLE
Github archive automation incorrectly flagging issues

### ISSUE THREAD

**Issue by irfan-dahir** [jikan-me/jikan#454]
https://github.com/jikan-me/jikan/blob/5ee048c2ad235e7cd65b6b251595be97949f5b8c/.github/workflows/archive.yaml#L24

The following issues have the `feature request` labels yet they were added into archiving. 
#391 #277 

https://github.com/jikan-me/jikan/issues/287 was unaffected interestingly

Any clue @pushrbx ?

**Comment by pushrbx** [comment]
Wrong version of the actions/stale action. My bad.

**Comment by pushrbx** [comment]
@irfan-dahir not sure if this is fixed. The action still gives warnings:
https://github.com/jikan-me/jikan/runs/7267390454?check_suite_focus=true
