### ISSUE TITLE
Parser should return total number of aired episodes

### ISSUE THREAD

**Issue by pushrbx** [jikan-me/jikan#464]
jikan-me/jikan-rest#260

<img width="1071" alt="Screenshot 2022-07-11 at 3 01 51 PM" src="https://user-images.githubusercontent.com/87663026/178240225-d9b2b6a0-b4e8-4c67-9469-24434c483e2b.png">

**Comment by irfan-dahir** [comment]
Closing as of: https://github.com/jikan-me/jikan-rest/issues/260#issuecomment-1180629075
