### ISSUE TITLE
title_japanese dosen't return japanese /Episodes 

### ISSUE THREAD

**Issue by MohammedADev** [jikan-me/jikan#465]
https://api.jikan.moe/v4/anime/42963/episode
![chrome_WlSWlQyp0k](https://user-images.githubusercontent.com/40725969/178327334-9a419972-0191-46b0-894b-9bd19fd57b5e.png)
![chrome_D1knJDOJDl](https://user-images.githubusercontent.com/40725969/178327338-40260e42-1ff5-41b2-8de8-512cd7a6576b.png)
s

**Comment by irfan-dahir** [comment]
That is JSON encoded japanese. You need to JSON decode it
