### ISSUE TITLE
Reviews pagination endpoint error

### ISSUE THREAD

**Issue by hasnat123** [jikan-me/jikan#466]
I've noticed that for every anime the reviews pagination data shows that there aren't any other pages. This is what I see for all anime reviews:

`pagination:
    has_next_page: false
    last_visible_page: 1`

**Comment by ZenT3600** [comment]
I'm experiencing this issue too. I tried asking on the official discord for help, but no one is replying. Also, all other endpoints seem to be working fine for some reason.

**Comment by irfan-dahir** [comment]
Thanks for your patience. MAL [recently rehauled](https://myanimelist.net/forum/?topicid=2034720&show=0) the reviews a bit and added some new information to it. 

I'm working on a fix for this.

**Comment by irfan-dahir** [comment]
Closing this issue, please track it further here: https://github.com/jikan-me/jikan-rest/issues/281
