### ISSUE TITLE
Not able to access the api

### ISSUE THREAD

**Issue by TyFangXV** [jikan-me/jikan#467]
for some reason the domain name `jikan.moe ` is showing `This site can’t be reached`

**Comment by irfan-dahir** [comment]
It's working for me. Check if it's a firewall issue?

**Comment by PhantomPainX** [comment]
Working in my page too.

**Comment by TyFangXV** [comment]
> It's working for me. Check if it's a firewall issue?

checked it using tor browser and worked fine
