### ISSUE TITLE
Request show the name of the forum thread as well as the post #number.

### ISSUE THREAD

**Issue by cyber-sec0** [jikan-me/jikan#468]
When fetching https://myanimelist.net/forum/?topicid=2026447#msg66799688 using the api we could have the topic title and the reply number as well like "[MAL Bunkasai: Send decor and event ideas to the Student Council (#37)]

**Comment by irfan-dahir** [comment]
Sorry but we have no plans to support Forum parsing as the data is available through the MAL API.

MAL Docs: https://myanimelist.net/apiconfig/references/api/v2#operation/forum_topic_get
