### ISSUE TITLE
[ `Question` ] : Is it possible to get the database dump?

### ISSUE THREAD

**Issue by baseplate-admin** [jikan-me/jikan#474]
Hi there,

Thanks for making this awesome Project.

Now i was wondering if it was possible to get jikan.moe database dump from official instance. So that i can seed my own jikan instance without scraping MyAnimeList.

 Is this feature available?  ( or is it possible to add something like this? ) 

Thanks again,

I wish you guys a good day

**Comment by irfan-dahir** [comment]
Hi,

Sorry, we do not provide data dumps.
