### ISSUE TITLE
[ `Question` ] : Is it possible to get the total number of anime available in the database? 

### ISSUE THREAD

**Issue by baseplate-admin** [jikan-me/jikan#475]
Hi there, 

Its me again and i have a small question. 

Is it possible to get the total number of entries available in the database somehow?

For example 

Lets suppose that i want to seed my database using jikan.moe. Now i can do a while loop to get data from `api.jikan.moe/anime`. But this will continue forever ( unless i set a range ) 

Now the question here is that is it possible to get the total number of animes ( so that i can set the upper range ) 

Thanks :D

**Comment by irfan-dahir** [comment]
You can use the information in `pagination`
e.g https://api.jikan.moe/v4/anime

```
  "pagination": {
    "last_visible_page": 1008,
    "has_next_page": true,
    "current_page": 1,
    "items": {
      "count": 25,
      "total": 25184, // this is the total number of anime entires in the DB
      "per_page": 25
    }
  },
 ```

**Comment by baseplate-admin** [comment]
I got my answer
 Thanks for responding quickly. 

Oopps sorry i overlooked discord :)

Next time i will try contacting there. 

Thanks :D
