### ISSUE TITLE
php work??

### ISSUE THREAD

**Issue by CodingBDX** [jikan-me/jikan#484]
i try to use top manga in vanilla php (not framework)
i have install composer install jikan

but how to use it? i follow documentation, not work, not found jikan,nothing work..

thank for answer

**Comment by CodingBDX** [comment]
> This is how you make top manga request in Jikan.
> 
> ```
> $topManga = $jikan->getTopManga(new TopMangaRequest($page, $type))
> ```
> 
> You need to pass the respective Request class (`TopMangaRequest`) into the get API class (`getTopManga`).
> 
> Also, this API syntax is invalid: `$topManga = $jikan->TopManga();`
> 
> Can you check if your jikan version is `^v3` https://github.com/jikan-me/jikan/releases/tag/v3.3.2


okey but it's not write in documentation, where????
i try your code $topManga = $jikan->getTopManga(new TopMangaRequest($page, $type))
not found class getTopManga....

i try download zip version 3 but after download and launch composer install, what i do???

thank

**Comment by irfan-dahir** [comment]
You need to composer require jikan in your project. 
Please read into using composer.
https://metabox.io/composer-and-autoload-in-php/

The docs for jikan php are not upto date. I'd suggest using any IDE with intellisense auto complete like PHPStorm.

**Comment by CodingBDX** [comment]
Yes i do, it install lot depance but After, i do what?
Explain more please or update documentation Friends

**Comment by pushrbx** [comment]
Personally I had some issues installing jikan with composer version `2.2.6`, so after upgrading to `2.4.3` everything worked.
Here is a sample which works:      
[test_jikan.zip](https://github.com/jikan-me/jikan/files/9823591/test_jikan.zip)

You only have to extract it, and run `composer install` in the folder.

The steps I did:

```bash
mkdir test_jikan
cd test_jikan
composer init
```
![image](https://user-images.githubusercontent.com/6832715/196785625-0d66b5f8-f088-490e-852e-9cbe2aa81222.png)

**Comment by janvernieuwe** [comment]
Or you can use my api client. Tho that also works with composer.
https://github.com/janvernieuwe/jikan-jikanPHP

If you want to do PHP, I highly recomend reading up on composer usage and package management.

**Comment by CodingBDX** [comment]
hello friend, i have do the same thing like you, installation are good
my file composer.json
`{
    "name": "root/manga",
    "require": {
        "jikan-me/jikan": "^3.3"
    },
    "license": "MIT",
    "autoload": {
        "psr-4": {
            "Root\\Manga\\": "src/"
        }
    },
    "authors": [
        {
            "name": "CodingBDX",
            "email": ""
        }
    ]
}
`

and my index.php into src
`require '../vendor/autoload.php';

// require '../models/Manga.php';

use Jikan\MyAnimeList\MalClient;

$jikan = new MalClient();

$topManga = $jikan->getTopManga(new TopMangaRequest($page, $type));
`

and i have this error with xdebug
Fatal error: Uncaught Error: Class "TopMangaRequest" not found in /var/www/manga/src/index.php on line 11


thank for fast answer friend!

**Comment by CodingBDX** [comment]
> Or you can use my api client. Tho that also works with composer. https://github.com/janvernieuwe/jikan-jikanPHP
> 
> If you want to do PHP, I highly recomend reading up on composer usage and package management and use an intellisense IDE as @irfan-dahir suggested.

yes but you can explain, i download ans launch composer init, but after??? you explain not clear...

**Comment by janvernieuwe** [comment]
Please read up here https://phptherightway.com/#composer_and_packagist

**Comment by CodingBDX** [comment]
thank you for your helps, it's work for topmangarequest ;)

now, i try to convert the result of json top a array, but it's return
'TypeError: file_get_contents(): Argument #1 ($filename) must be of type string'

`$topMangas = $jikan->getTopManga(new TopMangaRequest(1, 'manga'));

// converte top json in php

$response = json_decode(file_get_contents($topMangas), true);`

**Comment by pushrbx** [comment]
The contents of the `$topMangas` is an instance of the `TopManga` class. You need to convert it to an `array` object to be able to export it as json. `file_get_contents` is a function to read files from the disk. It takes a file pointer or a file path as first argument.
You need to use the following function to convert the TopManga class instance to an array:
https://github.com/jikan-me/jikan/blob/master/src/Model/Top/TopManga.php#L70

**Comment by CodingBDX** [comment]
thank man
i do this $result = $topMangas->getResults();
and i call into foreach
`<body>
    <?php foreach ($result as $key => $manga) {
        echo $manga['title'];
    }
?>
`

but not work
nnot use object of type Jikan\Model\Top\TopMangaListItem as array in /var/www/html/manga/public/index.php o

**Comment by pushrbx** [comment]
Each element of the array is a `TopMangaListItem` instance.
https://github.com/jikan-me/jikan/blob/master/src/Model/Top/TopMangaListItem.php

Accordingly you need to use the getter functions to get each field.

**Comment by pushrbx** [comment]
Please don't forget about my Krispy Kremes and coffee: https://ko-fi.com/pushrbx

**Comment by CodingBDX** [comment]
you can show me one exemple, i try ->getTitle() but it' don't find method..

**Comment by pushrbx** [comment]
Using my previous example as a base:
```php
<?php
namespace Pushrbx\TestJikan;
require "vendor/autoload.php";

use Jikan\MyAnimeList\MalClient;
use Jikan\Request\Top\TopMangaRequest;

$jikan = new MalClient();
$topManga = $jikan->getTopManga(new TopMangaRequest(1, "manga"));
$results = $topManga->getResults();
print_r($results[0]->getTitle());

```

**Comment by CodingBDX** [comment]
i understand friend, that work, thank for your support!
