### ISSUE TITLE
Is it possible to make Related Anime always return a list?

### ISSUE THREAD

**Issue by zunjae** [jikan-me/jikan#49]
In my parser I map json keys to Java variables, example:

`@SerializedName("ranked") public int ranked;`

To parse the JSON, I use GSON, so my code looks like this

`Anime anime = gson.fromJson("here comes the json provided by Jikan");`

(to call the ranked variable, I use `anime.ranked`, Parsing and mapping to a Java object happens only in one line of code)

My problem is that Sequel on Jikan can either return a double List/Array, if the Anime has more than 1 sequel - or single Array when the Anime only has 1 sequel

To completely mitigate this issue (for me), making it always return a double array fixes it

Example current JSON:
```
    "Sequel": [
      "Clannad: After Story<\/a>",
      "\/anime\/4181\/Clannad__After_Story"
    ]
```

Example new situation
```
    "Sequel": [
     [
      "Clannad: After Story<\/a>",
      "\/anime\/4181\/Clannad__After_Story"
     ] // add other sequels here, comma separated
    ]
```

I was wondering if this is possible for Jikan, if not I'll just keep the 'Related Anime' off my app

Oh and to clarify, only return a list if there is an related Anime found of course.

PS: I am looking for solutions on my end, so if I manage to find it, I'll just close the issue

**Comment by irfan-dahir** [comment]
Sure, I can do that. It didn't occur to me it could cause an issue. 

Just to confirm, It'll be something like this
```
"related": [
"Foo":[ [], [], [] ],
"Bar":[ [] ] //even for 1 item, it'll encapsulate it within an array/list
]
```

Is this right?

**Comment by zunjae** [comment]
yes, exactly that!
