### ISSUE TITLE
[OFFICIAL] Generated Issue: ParserException

### ISSUE THREAD

**Issue by wokesdev** [jikan-me/jikan#493]
Please fill out the details below.

**Summary:**
When I opened this 48867's relations endpoint, it gives me this ParserException error. I don't know what the problem is, because other anime's relations seems not having this kind of problem. Can you look into this? Thanks!

**Steps to reproduce:**
Just open https://api.jikan.moe/v4/anime/48867/relations and it will give this error.

 ### Additional Details 
 **Jikan Parser Version**: ```v3.3.2@405f5f5e5e185a074b227211a06ceba835f53e08```
**PHP:** ```8.0.19```
**Redis**: ```Connected```
**Exception:** ```Jikan\Exception\ParserException```
**Code:** ```0```
**Message:** ```Failed to parse 'https://myanimelist.net/anime/48867/'```
**Trace:** ```/var/www/jikan-rest/vendor/jikan-me/jikan/src/Exception/ParserException.php on line 24```
**Request:** `GET /v4/anime/48867/relations`

**Comment by irfan-dahir** [comment]
Resolved
