### ISSUE TITLE
getAnimeEpisodes incorrectly reporting that there is a next page

### ISSUE THREAD

**Issue by PythonCoderAS** [jikan-me/jikan#510]
Requesting https://api.jikan.moe/v4/anime/50265/episodes?page=1 gives me:

```json
{
  "pagination": {
    "last_visible_page": 1,
    "has_next_page": true
  },
  "data": [...]
}
```

This is despite `last_visible_page` being 1.

**Comment by pushrbx** [comment]
This has been fixed, however the fix hasn't been deployed yet to the public API. See: https://github.com/jikan-me/jikan/pull/502
