### ISSUE TITLE
Does Myanimelist IP ban?

### ISSUE THREAD

**Issue by baseplate-admin** [jikan-me/jikan#519]
Hi, 

I was wondering if it is possible to get ip banned for running a local instance of jikan or in general scraping myanimelist :)

**Comment by irfan-dahir** [comment]
It is possible that MAL could IP ban you for making too many requests afaik.

**Comment by baseplate-admin** [comment]
Hmm one more question ( sorry if it's a bit personal )

Did you folks ever get banned on production server ?

**Comment by irfan-dahir** [comment]
No, I requested MAL to whitelist us. However, we do get the normal rate limitations and try to keep it under that.

**Comment by baseplate-admin** [comment]
Thank you very much
