### ISSUE TITLE
getTopAnime with filter of 'upcoming' doesn't return any data

### ISSUE THREAD

**Issue by TruePadawan** [jikan-me/jikan#524]
![image](https://github.com/jikan-me/jikan/assets/71678062/cfe3804b-2aa0-4016-8983-ce91a1003eb8)

**Comment by irfan-dahir** [comment]
Thanks for reporting. This is a duplicate of https://github.com/jikan-me/jikan-rest/issues/388 so I'll close this one. You can follow track the issue there.
