### ISSUE TITLE
Endpoint to fetch the inidividual episode ratings.

### ISSUE THREAD

**Issue by P529** [jikan-me/jikan#525]
Hey, 

Ive stumbled upon your api after being quite frustrated with the minimal API that MAL is providing. One thing that I think could be useful would be to fetch the individual episode rating from https://myanimelist.net/anime/[ID]/[ANIMENAME]/episode 

Best regards,
P529

**Comment by irfan-dahir** [comment]
Hi, sorry for the late response.

We're already parsing this. https://api.jikan.moe/v4/anime/1/episodes
It's returned as `score`
