### ISSUE TITLE
Manga Review data often missing due to bad parsing

### ISSUE THREAD

**Issue by majora2007** [jikan-me/jikan#526]
### Current Behavior

https://api.jikan.moe/v4/manga/62795/reviews returns nothing, but
https://myanimelist.net/manga/62795/Tomodachi_Game?q=Tomadachi%20Game&cat=manga has reviews

I noticed there were existing issues opened around the anime endpoint and 500 errors, but in this case, I'm getting nothing back (empty result), however there should be data present.

### Expected Behavior

The reviews on the website should be reproduced

### Steps To Reproduce

1. Hit https://api.jikan.moe/v4/manga/62795/reviews
2. See no review
3. Open https://myanimelist.net/manga/62795/Tomodachi_Game?q=Tomadachi%20Game&cat=manga
4. Validate there are multiple review

This can be repeated for other manga, like Killing Bites

### Environment

```markdown
Used public API
Firefox/Chrome or via JikanDotNet
```

### Anything else?
This has been validated to be a parsing issue. 
https://github.com/jikan-me/jikan-rest/issues/407

**Comment by irfan-dahir** [comment]
Not a bug, responded here: https://github.com/jikan-me/jikan-rest/issues/407#issuecomment-1627759277
