### ISSUE TITLE
Anime reviews endpoint always returns page 1

### ISSUE THREAD

**Issue by jantosz** [jikan-me/jikan#531]
When I call the `reviews/anime/` endpoint,  it returns page 1 every time, no matter what page number I specify (`has_next_page` is true).

`{'last_visible_page': 1, 'has_next_page': True}`

**Comment by irfan-dahir** [comment]
@jantosz This is intended behavior for reviews.

Reviews are parsed from this page: https://myanimelist.net/reviews.php?t=anime

There is no pagination information only a "Next" button which helps identify whether `has_next_page` should be set to true. This is why `last_visible_page` falls back to `1`.

**Comment by Alucard2169** [comment]
@irfan-dahir that makes sense
