### ISSUE TITLE
Get an anime array by id array

### ISSUE THREAD

**Issue by fN9ne** [jikan-me/jikan#533]
Hello! I've run into a bit of an issue. I have an array of anime IDs, and I need to retrieve all the anime associated with these IDs. In the **API documentation**, I could only find the "**getAnimeById**" method.

Here's the situation: I have an array of **80 IDs**, and when I try to fetch all this data, I naturally get a **429 Too Many Requests** error.

Is there a way for me to send an array of IDs in the request and get the data I need?

I kindly request your assistance with my problem. Thanks in advance <3.

**Comment by pushrbx** [comment]
There is no such endpoint at the moment. Some of us in the community we get around this limitation by self-hosting the API.
