### ISSUE TITLE
🐛 Relations return empty response

### ISSUE THREAD

**Issue by obaidabit** [jikan-me/jikan#550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when you request the relations URL for an anime you get nothing.

### Steps To Reproduce

1. request this URL `https://api.jikan.moe/v4/anime/20/relations`
2. you get  `{"data":[]}`

**Comment by laxuscullen** [comment]
Can confirm, possibly due to the ui changes in mal

**Comment by pushrbx** [comment]
Superseded by: https://github.com/jikan-me/jikan/issues/551
