### ISSUE TITLE
🐛 [OFFICIAL] Generated Issue: ParserException

### ISSUE THREAD

**Issue by Sambld** [jikan-me/jikan#554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The API has returned an error: 
```Jikan\Exception\ParserException```
Status code: ```0```
Message: ```Failed to parse 'https://myanimelist.net/anime/56165/'```
Trace: ```/var/www/jikan-rest/vendor/jikan-me/jikan/src/Exception/ParserException.php on line 24```

### Expected Behavior

The API should have returned a successful response with data.

### Steps To Reproduce

Http Request: `GET /v4/anime/56165

### Environment

```markdown
OS: Windows 10 
Browser: Brave
```

**Comment by maxkagamine** [comment]
Same for https://myanimelist.net/anime/40389/, if that helps.

**Comment by laxuscullen** [comment]
same on https://api.jikan.moe/v4/anime/56731/full

**Comment by wokesdev** [comment]
Same on https://api.jikan.moe/v4/anime/50114/full

**Comment by irfan-dahir** [comment]
Thanks for reporting. I've pushed out a hotfix (https://github.com/jikan-me/jikan/releases/tag/v4.0.11) which resolves this issue. Please feel free to re-open or create a new issue if it occurs again.
