### ISSUE TITLE
🐛 UpstreamException

### ISSUE THREAD

**Issue by wokesdev** [jikan-me/jikan#556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Some URL is returning response like this:
```
{
  "status": 500,
  "type": "UpstreamException",
  "message": "Request to MyAnimeList.net failed. MyAnimeList.net may be down/unavailable, refuses to connect or took too long to respond. Please try again later.",
  "error": "SSL certificate problem: certificate has expired for \"https://myanimelist.net/anime/59032/\"."
}
```
Is this because the anime is still on "pending approval"? But usually I can still fetch the data from not approved anime. And I think this happened on uncached response.

### Expected Behavior

Real data response like:
```
{
  "data": {
    "mal_id": 57519,
    "url": "https://myanimelist.net/anime/57519/Boku_no_Hero_Academia__Memories",
    ...
  }
}
```

### Steps To Reproduce

1. Open this URL: https://api.jikan.moe/v4/anime/59032/full
2. UpstreamException error is shown

### Environment

```markdown
- OS: Windows 11
- Browser: Opera GX LVL 5 (core: 109.0.5097.100)
```

**Comment by irfan-dahir** [comment]
Resolved, thanks for reporting. This is a yearly tradition. :)

**Comment by wokesdev** [comment]
Thank you!
