### ISSUE TITLE
🐛 BadResponseException

### ISSUE THREAD

**Issue by vladStar223** [jikan-me/jikan#560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

{
  "status": 504,
  "type": "BadResponseException",
  "message": "Jikan failed to connect to MyAnimeList. MyAnimeList may be down/unavailable or refuses to connect",
  "error": null
}

### Expected Behavior

"data": [
{
"url": "https://myanimelist.net/profile/vlad32kolm",
"username": "vlad32kolm",
"images": {},
"last_online": "string"
}
],

### Steps To Reproduce

 open this https://api.jikan.moe/v4/users
and get BadResponseException

### Environment

```markdown
- OS: Windows 11
- Browser: Yandex.Browser:
v.24.7.0.0 (Windows NT 4.0)
```

**Comment by irfan-dahir** [comment]
Issue should be resolved now.

**Comment by vladStar223** [comment]
thank  you
