### ISSUE TITLE
🐛 [OFFICIAL] Generated Issue: ParserException

### ISSUE THREAD

**Issue by IsmailIbrahim5** [jikan-me/jikan#561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The API has returned an error: 
```Jikan\Exception\ParserException```
Status code: ```0```
Message: ```Failed to parse 'https://myanimelist.net/anime/53888/_/episode/1'```
Trace: ```/var/www/jikan-rest/vendor/jikan-me/jikan/src/Exception/ParserException.php on line 24```

### Expected Behavior

The API should have returned a successful response with data.

### Steps To Reproduce

Http Request: `GET /v4/anime/53888/episodes/1

**Comment by irfan-dahir** [comment]
Fixed with release [v4.0.12](https://github.com/jikan-me/jikan/releases/tag/v4.0.12). 

Note: On the public REST API, please wait 24-48 hours for any existing cache to be replaced.
