### ISSUE TITLE
Incorrect datatype with Licensor and Studio when there are more than 1 producer

### ISSUE THREAD

**Issue by zunjae** [jikan-me/jikan#57]
`licensor` may say `false` whenever an Anime has more than 1 producer (or some other reason, am not sure)

Example Anime:

https://jikan.me/api/v1.2/anime/8536

Note: this will break certain parsers which rely on the correct datatype in the json file

**Comment by irfan-dahir** [comment]
Licensor and other data will return NULL whenever there's no data available for it (from now on).
