### ISSUE TITLE
hi,boy,, how to  get  the   Anime ID ??

### ISSUE THREAD

**Issue by yt7649757** [jikan-me/jikan#60]
such as  anime/{id} ,,, i dont't  konw  the  id  where to  get ?  Why not provide an interface to show all lists

**Comment by irfan-dahir** [comment]
Hi! 
Jikan is an unofficial API for MyAnimeList.net
You can get the anime/manga/person/character IDs from there.

For example, if you want to parse the data from `https://myanimelist.net/anime/1`, which is MAL's anime ID for Cowboy Bepop.
Then the endpoint will be `anime/{id}` in Jikan.

MAL Link: https://myanimelist.net/anime/1
Jikan Link: https://jikan.me/api/anime/1

Basically, the IDs are mapped directly with MyAnimeLists'.

**Mapping**
`myanimelist.net` -> `jikan.me/api/`

`myanimelist.net/anime/{id}` -> `anime/{id}`
`myanimelist.net/manga/{id}` -> `manga/{id}`
`myanimelist.net/people/{id}` -> `person/{id}` (note: it's **person** in Jikan)
`myanimelist.net/character/{id}` -> `character/{id}`

Let me know if I can assist you any further!

**Comment by yt7649757** [comment]
Can you not only get information about one anime at a time!
Every anime id needs to be found on your website? 
Is there an interface to provide that kind of data?
If not,After all, anime related interfaces  are harder to find.
---------------------------------------------------------------------
Does the search interface support English only?
---------------------------------------------------------------------
The anime on your website is free to watch? Is there an update every week?
---------------------------------------------------------------------
 Look forward to your reply!

**Comment by irfan-dahir** [comment]
@yt7649757 Jikan is **not** affiliated with MyAnimeList in any way. Jikan is a web scraper which parses data from MyAnimeLists' web pages.

> Does the search interface support English only?

MyAnimeList is available in English only as far as I know.

> The anime on your website is free to watch?

If you're referring to Jikan.me, this is **not** an anime streaming site. If you're referring to MyAnimeList.net, this is **not** an anime streaming site either. 

>  Is there an update every week?

The data on MyAnimeList is updated quite frequently and Jikan **parses** the data accordingly.


Regarding the "interface" you're looking for which gives you all anime IDs in raw data, MyAnimeList does not have anything like this. But there are a few ways around these.

1. Download the list of peoples' who have the most watched anime. 
 -> https://myanimelist.net/forum/?topicid=641247
You can do this by the following call from MyAnimeList's official API.
`https://myanimelist.net/malappinfo.php?u=Nekomata1037&status=all&type=anime`
As you can see, replace my username **Nekomata1037** with the username of someone from the thread I linked you.


2. Use MyAnimeList's (outdated) SiteMap 
 -> https://myanimelist.net/sitemap/anime-000.xml

3. Parse this: https://myanimelist.net/info.php?search=%25%25%25&go=relationids&divname=relationGen1 to get every single anime/manga on MyAnimeList.

**Comment by yt7649757** [comment]
oh, I always thought this MyAnimeList site was created by you!
I'll try to use the method you told me , thank you for your help!

**Comment by irfan-dahir** [comment]
Glad it was of help!

**Comment by subarusakaguchi** [comment]
So, i was in need of all anime Ids from MAL, and using [this link](https://myanimelist.net/info.php?search=%25%25%25&go=relationids&divname=relationGen1), i scraped the data with puppeteer and nodejs, i hope this help someone

[Here ](https://github.com/subarusakaguchi/mal-scrap)is the code i used

And [here ](https://raw.githubusercontent.com/subarusakaguchi/mal-scrap/main/animeIds.txt)is all the ids (12/12/2022) in a JS Array format.

**Comment by pushrbx** [comment]
@subarusakaguchi 
> So, i was in need of all anime Ids from MAL, and using [this link](https://myanimelist.net/info.php?search=%25%25%25&go=relationids&divname=relationGen1), i scraped the data with puppeteer and nodejs, i hope this help someone
> 
> [Here ](https://github.com/subarusakaguchi/mal-scrap)is the code i used
> 
> And [here ](https://raw.githubusercontent.com/subarusakaguchi/mal-scrap/main/animeIds.txt)is all the ids (12/12/2022) in a JS Array format.

There is a well maintained list of ids already:
https://github.com/seanbreckenridge/mal-id-cache, which Jikan is already using.

**Comment by sammyMax67** [comment]
How can i create a search query with the known ids
