### ISSUE TITLE
[Person] More

### ISSUE THREAD

**Issue by irfan-dahir** [jikan-me/jikan#61]
Not parsing anymore

**Comment by nicharesuk** [comment]
Hey I don't know if this is apart of this issue or not but the person's website value is sometimes corrupted with html data, for example:
http://jikan.me/api/person/692 
or 
http://jikan.me/api/person/873

**Comment by nicharesuk** [comment]
After some googling and playing around I think what might work best is if you use the "non-greedy" flag in your groups, e.g.:

<span class="dark_text">Website:</span> <a href="(.*?)">(.*?)</a>

Here's an example of it working:

https://regex101.com/r/edmRQB/1

**Comment by irfan-dahir** [comment]
Hi @nicharesuk , thank you for bringing this to my attention and providing a solution. Allow me a few days to address this issue!

**Comment by nicharesuk** [comment]
Another, and potentially cleaner, option other than using regex would be to use an HTML parser. I think PHP has one built in that could be used. That way you don't have to worry about regex doing something unexpected and you can be sure it's MAL whose changed things.

**Comment by irfan-dahir** [comment]
@nicharesuk I've pushed a hotfix for these the website issues and some other malformed data. 
https://jikan.me/api/v1.2/person/692
The non-greedy flag did the trick, kindly use endpoint `v1.2`
`https://jikan.me/api/v1.2/{request}/{param}`

I used ReGex since I had more experience with it, but you're right. ReGex is *not* the way to go with web parsing. I will definitely change it in the future - just not now due to lack of time.

**Comment by irfan-dahir** [comment]
Finally fixed! It's working amazingly good.

Available in JikanPHP 1.0.0+ or REST 2.0+
