### ISSUE TITLE
[Anime|Manga] Year

### ISSUE THREAD

**Issue by irfan-dahir** [jikan-me/jikan#64]
The year it was released/published.

Not same as **premiered** for Anime; it'll only be a 4 digit integer value stating the year.

**Comment by Suriteka** [comment]
If we are looking to the published value on Manga it returns us this.
<img width="373" alt="capture d ecran 2017-10-05 a 21 28 43" src="https://user-images.githubusercontent.com/31373819/31248520-51f936cc-aa14-11e7-98cc-a5b784f555ad.png">

If I understand your request, you want something like ['published']=> (int) 1994 ?

**Comment by irfan-dahir** [comment]
@Suriteka That's the request I got from a developer via email. It won't be taking over the `published` parameter, rather would be a new one.
Possibly something like; `year`. Or `start_year` and `end_year`.

What do you think of this request?

**Comment by Suriteka** [comment]
Let's do that then. ✌️

**Comment by irfan-dahir** [comment]
Just reviewed this change request. I won't be doing it for the following reasons:

- The data already exists in the `premiered` key and can be extracted from within by the developer
- You'd never get a fixed format since a lot of the airing anime on MAL don't possess the end year data or simply the format is missing or is incorrect - bad data.
