### ISSUE TITLE
Retain newlines in synopsis

### ISSUE THREAD

**Issue by zunjae** [jikan-me/jikan#66]
I'm not sure what the possible side effects are and if this is possible, but it would be cool if newlines in the synopsis could (optionally) be retained with your parser. This will help reading the huge wall of text on some Anime.

Example link: http://jikan.me/api/v1.2/anime/1

Example current output: `(...) Bebop are two such individuals. Mellow and carefree Spike Spiegel (...)`

Example desired output: `(...) Bebop are two such individuals.<br><br>Mellow and carefree Spike Spiegel (...)`

Either \n or `<br>` should be fine

**Comment by irfan-dahir** [comment]
@zunjae Right now, the synopsis data is extracted from the meta tag on the page, which doesn't have new lines.  It's straightforward as this `~<meta property="og:description" content="(.*)">~`.

In the early alpha builds, it was done through page parsing, (see [here](https://github.com/jikan-me/jikan/blob/c72f0113e711a2007765a0246e96945c4fc8b142/mal-uapi.php#L216)). which was rather inconvenient, slower, and a mess as the parsing could never be consistent with *every* anime/manga. So I switched it to a much better alternative.

I could try doing that, but I wouldn't promise clean parses for every response as MAL's html is a mess to begin with.

**Comment by zunjae** [comment]
Nah it's okay. I can imagine it breaking even if MAL changes one minor thing on their site. Also cleaning it would be pain. Thanks for the quick reply
