### ISSUE TITLE
Trailing whitespace in single named characters

### ISSUE THREAD

**Issue by AWConant** [jikan-me/jikan#67]
I only tested this with a few characters, but it appears that characters that do not have a first name and last name are returning with a single trailing whitespace on their 'name' attribute.

A few character IDs to test:

https://jikan.me/api/character/4 has a name attribute of 'Ein ', but I expect 'Ein'.
https://jikan.me/api/character/425 has a name attribute of 'Ginko ', but I expect 'Ginko'.

**Comment by irfan-dahir** [comment]
Thanks for letting me know! Will fix.

**Comment by irfan-dahir** [comment]
Fixed! Use endpoint v1.2!
