### ISSUE TITLE
Missing name attribute

### ISSUE THREAD

**Issue by AWConant** [jikan-me/jikan#68]
I don't know if this is a more pervasive problem, but the character endpoint does not return the name for a particular character (the key is missing from the response).

https://jikan.me/api/character/17128

**Comment by irfan-dahir** [comment]
This is very odd. I'll look into it.

**Comment by irfan-dahir** [comment]
Fixed. https://jikan.me/api/v1.2/character/17128

Use API endpoint `https://jikan.me/api/v1.2/` for the patched results.
