### ISSUE TITLE
[Feature] Auto update data for titles that has extended aired date

### ISSUE THREAD

**Issue by lenisko** [jikan-me/jikan#69]
Hello there.

I'm not sure how often you're pulling updates for titles, as I can see it's not withing 24hours for sure.
Anyway what do you think about additional pull of newest data using cron by simply checking aired date on data you own? this might be tricky, as format of aired data is... not so obvious.

There's JSON of title which has already changed [example.txt](https://github.com/jikan-me/jikan/files/1443678/example.txt)

Cheers!

**Comment by irfan-dahir** [comment]
Hi lenisko, currently the cache is expires after 3 days and any new request for an anime is updated is that expiration is detected.

What you've suggested is planned for the upcoming update - REST v2.0. A higher priority on anime that are currently airing or have yet to be aired - as frequent changes are made to them.

**Comment by irfan-dahir** [comment]
hi! Apparently I debugged this case and found out that the cache system was oddly not working for many cases. All this has been fixed with the 2.0 Endpoint.

https://api.jikan.me
Docs: https://jikan.docs.apiary.io

Will also be adding a cron to have airing titles update faster than normal ones.
