### ISSUE TITLE
[Character] Request hangs forever on certain IDs

### ISSUE THREAD

**Issue by BlackSynder** [jikan-me/jikan#77]
I don't have a lot to go on here, but I noticed this specifically on ID `151067`. I noticed the huge hang then failure in my wrapper but then when I manually went to check it, the API just didn't respond.

EDIT: It might be because this is a rather new-ish manga so the character might not be cached yet? Not sure exactly how it works but most characters do work as expected (haven't seen this with any other character as of yet)

**Comment by DeLeersnijderYentl** [comment]
The API itself is down. I can't even access the main site of the API.

**Comment by BlackSynder** [comment]
Yeah, it worked fine for others at the time of posting but now everything's down.

**Comment by irfan-dahir** [comment]
There were some hosting issues but that was resolved. This issue is occuring for me as well, I'll have a look into it.

**Comment by irfan-dahir** [comment]
Found the issue. It was occurring for characters without any voice actors. Good find!

This has been fixed across all endpoints.

http://jikan.me/api/v1.2/character/151067
