### ISSUE TITLE
API down?

### ISSUE THREAD

**Issue by BlackSynder** [jikan-me/jikan#81]
`api.jikan.me` isn't responding, but `jikan.me/api` is.

**Comment by irfan-dahir** [comment]
Looking into it.

**Comment by irfan-dahir** [comment]
Thanks for letting me know! Was a domain-level issue, which is now resolved. 👌

If this occurs again, please re-open this issue.

**Comment by noriellecruz** [comment]
API seems to be down again

**Comment by noriellecruz** [comment]
Nevermind, it's fine now.

**Comment by balu11698** [comment]
It seems to be down.
![image](https://user-images.githubusercontent.com/76583673/128624783-0f211851-bbed-472e-90ea-8680d7ce1654.png)

**Comment by irfan-dahir** [comment]
@balu11698 https://github.com/jikan-me/jikan/issues/357

**Comment by cliziamenotti** [comment]
Hello, Jikan API seems to be down again @irfan-dahir

**Comment by irfan-dahir** [comment]
@cliziamenotti There's an ongoing maintenance. More details on our [discord server](https://discord.com/channels/460491088004907029/612187872740769824/1115138185505288265).

**Comment by cliziamenotti** [comment]
thank you for replying so quickly !
